source :rubygems

gem 'cucumber', '~> 1.1.8'
gem 'httparty', '~> 0.10.0'
gem 'minitest', '~> 3.0.0'
gem 'nokogiri', '~> 1.8.1'

group :kitchen  do
  gem 'test-kitchen', :git => 'git@github.com:opscode/test-kitchen.git'
end
