# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_auth', models.DateTimeField(null=True)),
                ('last_2fa', models.DateTimeField(null=True)),
            ],
        ),
    ]
