# Generated by Django 2.2.4 on 2020-01-03 15:02

import django.core.files.storage
from django.db import migrations, models
import sessionals.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionals', '0004_add_sessionals_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionalattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=sessionals.models.sessional_attachment_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='sessionalcontract',
            unique_together=set(),
        ),
    ]
