# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 11:43


import autoslug.fields
import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='slug_string', unique_with=('unit',))),
                ('title', models.CharField(blank=True, max_length=4, null=True)),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('pref_first_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Preferred First Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('quote', b'Quote'), ('photo', b'Photo'), ('employer', b'Employer/Job')], max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='slug_string', unique_with=('contact',))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(max_length=500, null=True, upload_to=b'')),
                ('deleted', models.BooleanField(default=False)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.Contact')),
            ],
        ),
    ]
