# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 14:04


from django.db import migrations, models
import relationships.handlers


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_add_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(b'funding', relationships.handlers.FundingEvent), (b'employer', relationships.handlers.EmployerEvent), (b'quote', relationships.handlers.QuoteEvent), (b'photo', relationships.handlers.PhotoEvent), (b'resume', relationships.handlers.ResumeEvent), (b'relationsh', relationships.handlers.RelationshipEvent), (b'facultycon', relationships.handlers.FacultyConnectionEvent), (b'links', relationships.handlers.LinksEvent), (b'followups', relationships.handlers.FollowUpEvent), (b'awards', relationships.handlers.AwardEvent), (b'partnershi', relationships.handlers.PartnershipEvent), (b'participat', relationships.handlers.ParticipationEvent), (b'acknowledg', relationships.handlers.AcknowledgementEvent), (b'eac', relationships.handlers.EACEvent), (b'alumnus', relationships.handlers.AlumnusEvent), (b'field', relationships.handlers.FieldEvent), (b'notes', relationships.handlers.NotesEvent)], max_length=25),
        ),
    ]
