# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 15:07


from django.db import migrations, models
import django.db.models.deletion
import relationships.handlers

def set_last_modified(apps, schema_editor):
    Event = apps.get_model("relationships", "event")
    for event in Event.objects.all():
        if not event.last_modified:
            event.last_modified = event.timestamp
            event.last_modified_by = None
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_extend_length_of_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(b'employer', relationships.handlers.EmployerEvent), (b'quote', relationships.handlers.QuoteEvent), (b'photo', relationships.handlers.PhotoEvent), (b'resume', relationships.handlers.ResumeEvent), (b'relationship', relationships.handlers.RelationshipEvent), (b'facultyconnection', relationships.handlers.FacultyConnectionEvent), (b'links', relationships.handlers.LinksEvent), (b'followups', relationships.handlers.FollowUpEvent), (b'awards', relationships.handlers.AwardEvent), (b'funding', relationships.handlers.FundingEvent), (b'partnership', relationships.handlers.PartnershipEvent), (b'participation', relationships.handlers.ParticipationEvent), (b'acknowledgement', relationships.handlers.AcknowledgementEvent), (b'eac', relationships.handlers.EACEvent), (b'alumnus', relationships.handlers.AlumnusEvent), (b'field', relationships.handlers.FieldEvent), (b'notes', relationships.handlers.NotesEvent)], max_length=25),
        ),
        migrations.RunPython(set_last_modified)
    ]
