# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import relationships.handlers
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_add_last_modified_and_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relationships.Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('awards', relationships.handlers.AwardEvent), ('eac', relationships.handlers.EACEvent), ('employer', relationships.handlers.EmployerEvent), ('facultyconnection', relationships.handlers.FacultyConnectionEvent), ('field', relationships.handlers.FieldEvent), ('followups', relationships.handlers.FollowUpEvent), ('funding', relationships.handlers.FundingEvent), ('links', relationships.handlers.LinksEvent), ('relationship', relationships.handlers.RelationshipEvent), ('notes', relationships.handlers.NotesEvent), ('partnership', relationships.handlers.PartnershipEvent), ('acknowledgement', relationships.handlers.AcknowledgementEvent), ('participation', relationships.handlers.ParticipationEvent), ('photo', relationships.handlers.PhotoEvent), ('quote', relationships.handlers.QuoteEvent), ('resume', relationships.handlers.ResumeEvent), ('alumnus', relationships.handlers.AlumnusEvent)], max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='eventattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=relationships.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='eventattachment',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='relationships.Event'),
        ),
    ]
