# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import relationships.models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0006_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=relationships.models.attachment_upload_to),
        ),
    ]
