# Generated by Django 4.2.30 on 2026-08-27 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0027_auto_20250827_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='e.g. "minimum_wage"', max_length=100, validators=[django.core.validators.RegexValidator(message='Keys must start with a letter and contain only lowercase letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('label', models.CharField(help_text='e.g. "Minimum Wage"', max_length=200)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('email', 'Email'), ('url', 'URL'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', max_length=20)),
                ('value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='', help_text='Any notes about this variable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, help_text='Leave blank for the global default value.', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.unit')),
            ],
            options={
                'unique_together': {('key', 'unit')},
            },
        ),
    ]
