services:

  mysql:
    image: 'mariadb:11.8'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=dbname
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped
    healthcheck: # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      interval: 10s
      start_period: 5s
    networks:
      - internal

  smtp4dev:
    image: 'rnwood/smtp4dev'
    ports:
      - "8025:80"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
    networks:
      - internal
      - external