services:

  mysql:
    extends:
      file: compose-dev-services.yml
      service: mysql

  smtp4dev:
    extends:
      file: compose-dev-services.yml
      service: smtp4dev

  rabbitmq:
    extends:
      file: compose-base.yml
      service: rabbitmq
    secrets:
      - rabbitmq-default-password

  elasticsearch:
    extends:
      file: compose-base.yml
      service: elasticsearch
    secrets:
      - elastic-initial-password

  memcached:
    extends:
      file: compose-base.yml
      service: memcached

  nginx:
    extends:
      file: compose-base.yml
      service: nginx
    # build:
    #   args:
    #     - SERVE_HOSTS=coursys-demo.selfip.net coursys-test.selfip.net
    #     - FORWARD_HOSTS=olddomain.selfip.net

  logrotate:
    extends:
      file: compose-base.yml
      service: logrotate
 
  base:
    extends:
      file: compose-base.yml
      service: base
    build:
      args:
        - DEPLOY_MODE=demo
    depends_on:
      - mysql
    # environment:
    #   - MORE_ALLOWED_HOSTS=coursys-demo.selfip.net coursys-test.selfip.net
    #   - CSRF_TRUSTED_ORIGINS=http://coursys-demo.selfip.net http://coursys-test.selfip.net
    restart: no
    deploy:
      replicas: 0

  app:
    extends:
      service: base
    build:
      target: app
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      - web
    volumes:
      - /data/csrpt_auth:/csrpt_auth:rw,Z

  manage:
    extends:
      service: base
    build:
      target: manage
    restart: no
    deploy:
      replicas: 0
    networks:
      - backend
      - web
    volumes:
      - /data/csrpt_auth:/csrpt_auth:rw,Z

  admin:
    extends:
      service: base
    build:
      target: admin
    restart: no
    deploy:
      replicas: 0
    networks:
      - backend
      - web
    volumes:
      - /data/csrpt_auth:/csrpt_auth:rw,Z
      - /data/dynamic_config:/dynamic_config:rw,z

  celery-fast:
    extends:
      service: base
    build:
      target: celery
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - QUEUE=fast
      - CONCURRENCY=2
    networks:
      - backend
  celery-batch:
    extends: celery-fast
    volumes:
      - /data/db_backups:/db_backups:rw,Z
    environment:
      - QUEUE=batch
      - CONCURRENCY=2
  celery-email:
    extends: celery-fast
    environment:
      - QUEUE=email
      - CONCURRENCY=2
  celery-photo:
    extends: celery-fast
    environment:
      - QUEUE=photo
      - CONCURRENCY=5
  celery-sims:
    extends: celery-fast
    environment:
      - QUEUE=sims
      - CONCURRENCY=3
    volumes:
      - /data/csrpt_auth:/csrpt_auth:rw,Z

  beat:
    extends:
      service: base
    build:
      target: beat
    deploy:
      replicas: 1
    restart: unless-stopped
    networks:
      - backend


volumes:
  mysql:
  static:


networks:
  web:
  backend:


secrets:
  app-config:
    file: ./secrets/app-config.toml
  rabbitmq-default-password:
    file: ./secrets/rabbitmq-default-password
  elastic-initial-password:
    file: ./secrets/elastic-initial-password

