services:

  rabbitmq:
    extends:
      file: compose-base.yml
      service: rabbitmq
    volumes:

  elasticsearch:
    extends:
      file: compose-base.yml
      service: elasticsearch

  memcached:
    extends:
      file: compose-base.yml
      service: memcached

  nginx:
    extends:
      file: compose-base.yml
      service: nginx
    # build:
    #   args:
    #     - SERVE_HOSTS=coursys.sfu.ca fasit.sfu.ca
    #     - FORWARD_HOSTS=coursys.cs.sfu.ca courses.cs.sfu.ca

  base:
    extends:
      file: compose-base.yml
      service: base
    build:
      args:
        - DEPLOY_MODE=demo
    restart: no
    # environment:
    #   - MORE_ALLOWED_HOSTS=alternate-hostname.sfu.ca
    #   - CSRF_TRUSTED_ORIGINS=https://alternate-hostname.sfu.ca
    deploy:
      replicas: 0

  app:
    extends:
      service: base
    build:
      target: app
    init: true  # init sends appropriate TERM signals to gunicorn to restart cleanly
    restart: unless-stopped
    deploy:
      replicas: 2
  
  manage:
    extends:
      service: base
    build:
      target: manage
    restart: no
    deploy:
      replicas: 0

  celery-fast:
    extends:
      service: base
    build:
      target: celery
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - QUEUE=fast
      - CONCURRENCY=2
  celery-batch:
    extends: celery-fast
    volumes:
      - /data/db_backups:/db_backups:rw,Z
    environment:
      - QUEUE=batch
      - CONCURRENCY=2
  celery-email:
    extends: celery-fast
    environment:
      - QUEUE=email
      - CONCURRENCY=2
  celery-photo:
    extends: celery-fast
    environment:
      - QUEUE=photo
      - CONCURRENCY=5
  celery-sims:
    extends: celery-fast
    environment:
      - QUEUE=sims
      - CONCURRENCY=2
    volumes:
      - /data/csrpt_auth:/csrpt_auth:rw,Z

  celerybeat:
    extends:
      service: base
    build:
      target: beat
    deploy:
      replicas: 1
    restart: unless-stopped

  csrpt-test:  # temporary container to test csrpt auth without needed anything else started
    build:
      context: .
      dockerfile: docker/app.Dockerfile
      target: base
      args:
        - UID=888
        - DEPLOY_MODE=production
    volumes:
      - ./data/csrpt_auth:/csrpt_auth:rw,Z
    secrets:
      - app-config
    deploy:
      replicas: 0
    restart: no
    networks:
      - internal


volumes:
  static:


networks:
  internal:
  external:


secrets:
  app-config:
    file: ./secrets/app-config.toml
