services:

  mysql:
    extends:
      file: compose-dev-services.yml
      service: mysql

  smtp4dev:
    extends:
      file: compose-dev-services.yml
      service: smtp4dev

  rabbitmq:
    extends:
      file: compose-base.yml
      service: rabbitmq
    volumes:
      - ./data/rabbitmq3:/var/lib/rabbitmq:rw

  elasticsearch:
    extends:
      file: compose-base.yml
      service: elasticsearch
    volumes:
      - ./data/elasticsearch5:/usr/share/elasticsearch/data:rw,z

  memcached:
    extends:
      file: compose-base.yml
      service: memcached

  nginx:
    extends:
      file: compose-base.yml
      service: nginx
    build:
      args:
        - SERVE_HOSTS=localhost
        - FORWARD_HOSTS=
    ports:
      - "8080:80"
    volumes:
      - ./data/nginx_logs:/nginx_logs:rw
      - ./data/dynamic_config:/dynamic_config:ro

  base:
    extends:
      file: compose-base.yml
      service: base
    build:
      args:
        - DEPLOY_MODE=proddev
    volumes:
      - ./data/submitted_files:/submitted_files:rw
    restart: no
    deploy:
      replicas: 0

  app:
    extends:
      service: base
    build:
      target: app
    init: true  # init sends appropriate TERM signals to gunicorn to restart cleanly
    restart: unless-stopped
    deploy:
      replicas: 1  # could be >1 if desired
  
  manage:
    extends:
      service: base
    build:
      target: manage
    restart: no
    deploy:
      replicas: 0

  celery-fast:
    extends:
      service: base
    build:
      target: celery
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - QUEUE=fast
      - CONCURRENCY=2
  celery-batch:
    extends: celery-fast
    volumes:
      - ./data/db_backups:/db_backups:rw
    environment:
      - QUEUE=batch
      - CONCURRENCY=2
  celery-email:
    extends: celery-fast
    environment:
      - QUEUE=email
      - CONCURRENCY=2
  celery-photo:
    extends: celery-fast
    environment:
      - QUEUE=photo
      - CONCURRENCY=5
  celery-sims:
    extends: celery-fast
    environment:
      - QUEUE=sims
      - CONCURRENCY=2

  celerybeat:
    extends:
      service: base
    build:
      target: beat
    deploy:
      replicas: 1
    restart: unless-stopped


volumes:
  mysql:
  static:


networks:
  internal:
  external:


secrets:
  app-config:
    file: ./secrets/app-config.toml