services:

  mysql:
    image: 'mariadb:11.8'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=dbname
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped
    healthcheck: # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      interval: 10s
      start_period: 5s
    networks:
      - internal

  smtp4dev:
    image: 'rnwood/smtp4dev'
    ports:
      - "8025:80"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
    networks:
      - internal
      - external

  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq

  elasticsearch:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch

  memcached:
    extends:
      file: docker-compose-base.yml
      service: memcached

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx

  base:
    extends:
      file: docker-compose-base.yml
      service: base
    build:
      args:
        - DEPLOY_MODE=demo

  app:
    extends:
      service: base
    build:
      target: app
    init: true  # init sends appropriate TERM signals to gunicorn to restart cleanly
    restart: unless-stopped
    deploy:
      replicas: 1  # could be >1 if desired
  
  manage:
    extends:
      service: base
    build:
      target: manage
    restart: no
    deploy:
      replicas: 0

  celery-fast:
    extends:
      service: base
    build:
      target: celery
    restart: unless-stopped
    environment:
      - QUEUE=fast
      - CONCURRENCY=2

  celery-batch:
    extends: celery-fast
    volumes:
      - /data/db_backups:/db_backups:rw,Z
    environment:
      - QUEUE=batch
      - CONCURRENCY=2
      
  celery-email:
    extends: celery-fast
    environment:
      - QUEUE=email
      - CONCURRENCY=2
  celery-photo:
    extends: celery-fast
    environment:
      - QUEUE=photo
      - CONCURRENCY=5
  celery-sims:
    extends: celery-fast
    environment:
      - QUEUE=sims
      - CONCURRENCY=2

  celerybeat:
    extends:
      service: base
    build:
      target: beat
    restart: unless-stopped


volumes:
  mysql:
  static:
  elasticsearch5:


networks:
  internal:
  external:
