version: '3'
services:

  rabbitmq:
    image: 'rabbitmq:3'
    restart: always
    ports:
      - "127.0.0.1:5672:5672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq:rw
    environment:
      - RABBITMQ_DEFAULT_USER=coursys
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=myvhost

  elasticsearch:
    image: 'elasticsearch:5.6.16'
    restart: always
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data:rw
    environment:
      - discovery.type=single-node

  memcached:
    image: 'memcached:latest'
    restart: always
    ports:
      - "127.0.0.1:11211:11211"

  ruby-markup:
    build:
      context: ruby-markup
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

