services:

  mysql:
    image: 'mariadb:11.8'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped
    healthcheck: # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      interval: 10s
      start_period: 5s
    networks:
      - internal

  smtp4dev:
    image: 'rnwood/smtp4dev'
    ports:
      - "8025:80"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/ || exit 1
      timeout: 5s
      interval: 60s
      start_period: 10s
    networks:
      - internal
      - external

  rabbitmq:
    image: 'rabbitmq:3'
    volumes:
      - /data/rabbitmq3:/var/lib/rabbitmq:rw,Z
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 30s
      interval: 30s
      start_period: 10s
    networks:
      - internal

  elasticsearch:
    image: 'elasticsearch:5.6.16'
    # ports:
    #   - "9200"
    #   - "9300"
    volumes:
      - elasticsearch5:/usr/share/elasticsearch/data:rw
    environment:
      - discovery.type=single-node
      - allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      timeout: 30s
      interval: 60s
      start_period: 15s
    networks:
      - internal

  memcached:
    image: 'memcached:1-alpine'
    restart: unless-stopped
    healthcheck:
      test: echo "version" | nc -vn -w 1 127.0.0.1 11211
      timeout: 5s
      interval: 60s
      start_period: 5s
    networks:
      - internal

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:80/static/icons/favicon.ico?healthcheck || exit 1
      timeout: 5s
      interval: 60s
      start_period: 5s
    volumes:
      - static:/static:ro
      - /data/nginx_logs:/nginx-logs:rw,Z
      - /data/nginx-config:/nginx-config:ro,z
    networks:
      - internal
      - external

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
      args:
        - UID=888
        - DEPLOY_MODE=${DEPLOY_MODE}
        - N_WORKERS=3
    init: true  # init sends appropriate TERM signals to gunicorn to restart cleanly
    depends_on:
      - rabbitmq
      - elasticsearch
      - memcached
      - mysql
    volumes:
      - static:/static:rw
      - /data/submitted_files:/submitted_files:rw,z
    restart: unless-stopped
    networks:
      - internal
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - RABBITMQ_USER
      - RABBITMQ_PASSWORD
      - RABBITMQ_VHOST
    deploy:
      replicas: 1
  
  celery-fast:
    extends: app
    healthcheck:
      test: curl --fail http://localhost:9000/ || exit 1
    deploy:
      replicas: 1
    command: ./docker/celery-worker.sh fast 2

  celery-batch:
    extends: celery-fast
    command: ./docker/celery-worker.sh batch 2
    volumes:
      - /data/db_backups:/db_backups:rw,Z
      
  celery-email:
    extends: celery-fast
    command: ./docker/celery-worker.sh email 2
  celery-photo:
    extends: celery-fast
    command: ./docker/celery-worker.sh photo 5
  celery-sims:
    extends: celery-fast
    command: ./docker/celery-worker.sh sims 2

  celerybeat:
    extends: celery-fast
    healthcheck:
      test: echo  # I see no meaningful check, except existing
    deploy:
      replicas: 1
    command: celery -A courses beat --loglevel INFO

volumes:
  mysql:
  static:
  elasticsearch5:

networks:
  internal:
  external:
