from index import index
from quick_search import quick_search
from not_found import not_found
#from view_all import view_all
from supervisor_index import supervisor_index
from all_promises import all_promises
from view import view
from grad_more_info import grad_more_info
from manage_supervisors import manage_supervisors
from remove_supervisor import remove_supervisor
#from XXXmanage_supervisors import XXXmanage_supervisors
#from XXX_update_supervisors import XXX_update_supervisors
from manage_requirements import manage_requirements
from manage_academics import manage_academics
from manage_status import manage_status
from manage_otherfunding import manage_otherfunding
from manage_promises import manage_promises
#from new import new
from new_program import new_program
from programs import programs
from requirements import requirements
from new_requirement import new_requirement
from import_applic import import_applic
from letter_templates import letter_templates
from new_letter_template import new_letter_template
from manage_letter_template import manage_letter_template
#from letters import letters
from view_all_letters import view_all_letters
from new_letter import new_letter
from get_letter_text import get_letter_text
from get_addresses import get_addresses
from get_letter import get_letter
from view_letter import view_letter
from search import search
#from search_results import search_results
from save_search import save_search
from delete_savedsearch import delete_savedsearch
from student_financials import student_financials
from financials import financials
from new_promise import new_promise
from manage_scholarship import manage_scholarship
from manage_scholarshipType import manage_scholarshipType
