# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import faculty.event_types.awards
import faculty.event_types.career
import faculty.event_types.info
import faculty.event_types.position
import faculty.event_types.teaching


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_add_letter_option_to_memos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerevent',
            name='event_type',
            field=models.CharField(choices=[(b'ADMINPOS', faculty.event_types.position.AdminPositionEventHandler), (b'APPOINT', faculty.event_types.career.AppointmentEventHandler), (b'AWARD', faculty.event_types.awards.AwardEventHandler), (b'COMMITTEE', faculty.event_types.info.CommitteeMemberHandler), (b'EXTERN_AFF', faculty.event_types.info.ExternalAffiliationHandler), (b'EXTSERVICE', faculty.event_types.info.ExternalServiceHandler), (b'FELLOW', faculty.event_types.awards.FellowshipEventHandler), (b'GRANTAPP', faculty.event_types.awards.GrantApplicationEventHandler), (b'NORM_TEACH', faculty.event_types.teaching.NormalTeachingLoadHandler), (b'LEAVE', faculty.event_types.career.OnLeaveEventHandler), (b'ONE_NINE', faculty.event_types.teaching.OneInNineHandler), (b'OTHER_NOTE', faculty.event_types.info.OtherEventHandler), (b'LABMEMB', faculty.event_types.info.ResearchMembershipHandler), (b'SALARY', faculty.event_types.career.SalaryBaseEventHandler), (b'STIPEND', faculty.event_types.career.SalaryModificationEventHandler), (b'SPCL_DEAL', faculty.event_types.info.SpecialDealHandler), (b'STUDYLEAVE', faculty.event_types.career.StudyLeaveEventHandler), (b'TEACHING', faculty.event_types.awards.TeachingCreditEventHandler), (b'TENUREAPP', faculty.event_types.career.TenureApplicationEventHandler), (b'ACCRED', faculty.event_types.career.AccreditationFlagEventHandler), (b'PROMOTION', faculty.event_types.career.PromotionApplicationEventHandler), (b'SALARYREV', faculty.event_types.career.SalaryReviewEventHandler), (b'CONTRACTRV', faculty.event_types.career.ContractReviewEventHandler), (b'RESUME', faculty.event_types.info.ResumeEventHandler)], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventconfig',
            name='event_type',
            field=models.CharField(choices=[(b'ADMINPOS', faculty.event_types.position.AdminPositionEventHandler), (b'APPOINT', faculty.event_types.career.AppointmentEventHandler), (b'AWARD', faculty.event_types.awards.AwardEventHandler), (b'COMMITTEE', faculty.event_types.info.CommitteeMemberHandler), (b'EXTERN_AFF', faculty.event_types.info.ExternalAffiliationHandler), (b'EXTSERVICE', faculty.event_types.info.ExternalServiceHandler), (b'FELLOW', faculty.event_types.awards.FellowshipEventHandler), (b'GRANTAPP', faculty.event_types.awards.GrantApplicationEventHandler), (b'NORM_TEACH', faculty.event_types.teaching.NormalTeachingLoadHandler), (b'LEAVE', faculty.event_types.career.OnLeaveEventHandler), (b'ONE_NINE', faculty.event_types.teaching.OneInNineHandler), (b'OTHER_NOTE', faculty.event_types.info.OtherEventHandler), (b'LABMEMB', faculty.event_types.info.ResearchMembershipHandler), (b'SALARY', faculty.event_types.career.SalaryBaseEventHandler), (b'STIPEND', faculty.event_types.career.SalaryModificationEventHandler), (b'SPCL_DEAL', faculty.event_types.info.SpecialDealHandler), (b'STUDYLEAVE', faculty.event_types.career.StudyLeaveEventHandler), (b'TEACHING', faculty.event_types.awards.TeachingCreditEventHandler), (b'TENUREAPP', faculty.event_types.career.TenureApplicationEventHandler), (b'ACCRED', faculty.event_types.career.AccreditationFlagEventHandler), (b'PROMOTION', faculty.event_types.career.PromotionApplicationEventHandler), (b'SALARYREV', faculty.event_types.career.SalaryReviewEventHandler), (b'CONTRACTRV', faculty.event_types.career.ContractReviewEventHandler), (b'RESUME', faculty.event_types.info.ResumeEventHandler)], max_length=10),
        ),
        migrations.AlterField(
            model_name='grant',
            name='label',
            field=models.CharField(db_index=True, help_text=b'for identification from FAST import', max_length=150),
        ),
        migrations.AlterField(
            model_name='memotemplate',
            name='event_type',
            field=models.CharField(choices=[(b'ADMINPOS', faculty.event_types.position.AdminPositionEventHandler), (b'APPOINT', faculty.event_types.career.AppointmentEventHandler), (b'AWARD', faculty.event_types.awards.AwardEventHandler), (b'COMMITTEE', faculty.event_types.info.CommitteeMemberHandler), (b'EXTERN_AFF', faculty.event_types.info.ExternalAffiliationHandler), (b'EXTSERVICE', faculty.event_types.info.ExternalServiceHandler), (b'FELLOW', faculty.event_types.awards.FellowshipEventHandler), (b'GRANTAPP', faculty.event_types.awards.GrantApplicationEventHandler), (b'NORM_TEACH', faculty.event_types.teaching.NormalTeachingLoadHandler), (b'LEAVE', faculty.event_types.career.OnLeaveEventHandler), (b'ONE_NINE', faculty.event_types.teaching.OneInNineHandler), (b'OTHER_NOTE', faculty.event_types.info.OtherEventHandler), (b'LABMEMB', faculty.event_types.info.ResearchMembershipHandler), (b'SALARY', faculty.event_types.career.SalaryBaseEventHandler), (b'STIPEND', faculty.event_types.career.SalaryModificationEventHandler), (b'SPCL_DEAL', faculty.event_types.info.SpecialDealHandler), (b'STUDYLEAVE', faculty.event_types.career.StudyLeaveEventHandler), (b'TEACHING', faculty.event_types.awards.TeachingCreditEventHandler), (b'TENUREAPP', faculty.event_types.career.TenureApplicationEventHandler), (b'ACCRED', faculty.event_types.career.AccreditationFlagEventHandler), (b'PROMOTION', faculty.event_types.career.PromotionApplicationEventHandler), (b'SALARYREV', faculty.event_types.career.SalaryReviewEventHandler), (b'CONTRACTRV', faculty.event_types.career.ContractReviewEventHandler), (b'RESUME', faculty.event_types.info.ResumeEventHandler)], help_text=b'The type of event that this memo applies to', max_length=10),
        ),
        migrations.AlterField(
            model_name='memotemplate',
            name='label',
            field=models.CharField(help_text=b'The name for this template (that you select it by when using it)', max_length=150, verbose_name=b'Template Name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='rank',
            field=models.CharField(blank=True, choices=[(b'LLEC', b'Limited-Term Lecturer'), (b'LABI', b'Laboratory Instructor'), (b'LECT', b'Lecturer'), (b'SLEC', b'Senior Lecturer'), (b'INST', b'Instructor'), (b'ASSI', b'Assistant Professor'), (b'ASSO', b'Associate Professor'), (b'FULL', b'Full Professor'), (b'URAS', b'University Research Associate'), (b'ADJC', b'Adjunct Professor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempgrant',
            name='label',
            field=models.CharField(help_text=b'for identification from FAST import', max_length=150),
        ),
    ]
