# Generated by Django 2.2.1 on 2019-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
