# Generated by Django 2.2.2 on 2019-06-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_do_not_require_title_for_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='rank',
            field=models.CharField(blank=True, choices=[('LLEC', 'Limited-Term Lecturer'), ('LABI', 'Laboratory Instructor'), ('LECT', 'Lecturer'), ('SLEC', 'Senior Lecturer'), ('INST', 'Instructor'), ('ASSI', 'Assistant Professor'), ('ASSO', 'Associate Professor'), ('FULL', 'Full Professor'), ('URAS', 'University Research Associate'), ('ADJC', 'Adjunct Professor'), ('POPP', 'Professor of Professional Practice')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='positiondocumentattachment',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
