# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import faculty.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_do_not_require_title_for_position_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=faculty.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='positiondocumentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=faculty.models.position_attachment_upload_to),
        ),
    ]
