# Generated by Django 5.2.17 on 2026-09-02 08:55

import faculty.event_types.awards
import faculty.event_types.career
import faculty.event_types.info
import faculty.event_types.position
import faculty.event_types.teaching
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0020_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "ADMINPOS",
                        faculty.event_types.position.AdminPositionEventHandler,
                    ),
                    ("APPOINT", faculty.event_types.career.AppointmentEventHandler),
                    ("AWARD", faculty.event_types.awards.AwardEventHandler),
                    ("COMMITTEE", faculty.event_types.info.CommitteeMemberHandler),
                    ("EXTERN_AFF", faculty.event_types.info.ExternalAffiliationHandler),
                    ("EXTSERVICE", faculty.event_types.info.ExternalServiceHandler),
                    ("FELLOW", faculty.event_types.awards.FellowshipEventHandler),
                    (
                        "GRANTAPP",
                        faculty.event_types.awards.GrantApplicationEventHandler,
                    ),
                    (
                        "NORM_TEACH",
                        faculty.event_types.teaching.NormalTeachingLoadHandler,
                    ),
                    ("LEAVE", faculty.event_types.career.OnLeaveEventHandler),
                    ("OTHER_NOTE", faculty.event_types.info.OtherEventHandler),
                    ("SALARY", faculty.event_types.career.SalaryBaseEventHandler),
                    ("RETIRE", faculty.event_types.career.RetirementEventHandler),
                    ("RESIGN", faculty.event_types.career.ResignationEventHandler),
                    (
                        "PROBATR",
                        faculty.event_types.career.ProbationaryReviewEventHandler,
                    ),
                    (
                        "TENPROAP",
                        faculty.event_types.career.TenurePromotionAssociateProfessorEventHandler,
                    ),
                    (
                        "ALTCA",
                        faculty.event_types.career.AlternateCareerPathEventHandler,
                    ),
                    (
                        "MODAPP",
                        faculty.event_types.career.ModifiedAppointmentEventHandler,
                    ),
                    ("ADDPAY", faculty.event_types.info.AddPayEventHandler),
                    (
                        "STIPEND",
                        faculty.event_types.career.SalaryModificationEventHandler,
                    ),
                    ("SPCL_DEAL", faculty.event_types.info.SpecialDealHandler),
                    ("STUDYLEAVE", faculty.event_types.career.StudyLeaveEventHandler),
                    ("TEACHING", faculty.event_types.awards.TeachingCreditEventHandler),
                    (
                        "TENUREAPP",
                        faculty.event_types.career.TenureApplicationEventHandler,
                    ),
                    (
                        "ACCRED",
                        faculty.event_types.career.AccreditationFlagEventHandler,
                    ),
                    (
                        "PROMOTION",
                        faculty.event_types.career.PromotionApplicationEventHandler,
                    ),
                    ("SALARYREV", faculty.event_types.career.SalaryReviewEventHandler),
                    (
                        "CONTRACTRV",
                        faculty.event_types.career.ContractReviewEventHandler,
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventconfig",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "ADMINPOS",
                        faculty.event_types.position.AdminPositionEventHandler,
                    ),
                    ("APPOINT", faculty.event_types.career.AppointmentEventHandler),
                    ("AWARD", faculty.event_types.awards.AwardEventHandler),
                    ("COMMITTEE", faculty.event_types.info.CommitteeMemberHandler),
                    ("EXTERN_AFF", faculty.event_types.info.ExternalAffiliationHandler),
                    ("EXTSERVICE", faculty.event_types.info.ExternalServiceHandler),
                    ("FELLOW", faculty.event_types.awards.FellowshipEventHandler),
                    (
                        "GRANTAPP",
                        faculty.event_types.awards.GrantApplicationEventHandler,
                    ),
                    (
                        "NORM_TEACH",
                        faculty.event_types.teaching.NormalTeachingLoadHandler,
                    ),
                    ("LEAVE", faculty.event_types.career.OnLeaveEventHandler),
                    ("OTHER_NOTE", faculty.event_types.info.OtherEventHandler),
                    ("SALARY", faculty.event_types.career.SalaryBaseEventHandler),
                    ("RETIRE", faculty.event_types.career.RetirementEventHandler),
                    ("RESIGN", faculty.event_types.career.ResignationEventHandler),
                    (
                        "PROBATR",
                        faculty.event_types.career.ProbationaryReviewEventHandler,
                    ),
                    (
                        "TENPROAP",
                        faculty.event_types.career.TenurePromotionAssociateProfessorEventHandler,
                    ),
                    (
                        "ALTCA",
                        faculty.event_types.career.AlternateCareerPathEventHandler,
                    ),
                    (
                        "MODAPP",
                        faculty.event_types.career.ModifiedAppointmentEventHandler,
                    ),
                    ("ADDPAY", faculty.event_types.info.AddPayEventHandler),
                    (
                        "STIPEND",
                        faculty.event_types.career.SalaryModificationEventHandler,
                    ),
                    ("SPCL_DEAL", faculty.event_types.info.SpecialDealHandler),
                    ("STUDYLEAVE", faculty.event_types.career.StudyLeaveEventHandler),
                    ("TEACHING", faculty.event_types.awards.TeachingCreditEventHandler),
                    (
                        "TENUREAPP",
                        faculty.event_types.career.TenureApplicationEventHandler,
                    ),
                    (
                        "ACCRED",
                        faculty.event_types.career.AccreditationFlagEventHandler,
                    ),
                    (
                        "PROMOTION",
                        faculty.event_types.career.PromotionApplicationEventHandler,
                    ),
                    ("SALARYREV", faculty.event_types.career.SalaryReviewEventHandler),
                    (
                        "CONTRACTRV",
                        faculty.event_types.career.ContractReviewEventHandler,
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="memotemplate",
            name="event_type",
            field=models.CharField(
                choices=[
                    (
                        "ADMINPOS",
                        faculty.event_types.position.AdminPositionEventHandler,
                    ),
                    ("APPOINT", faculty.event_types.career.AppointmentEventHandler),
                    ("AWARD", faculty.event_types.awards.AwardEventHandler),
                    ("COMMITTEE", faculty.event_types.info.CommitteeMemberHandler),
                    ("EXTERN_AFF", faculty.event_types.info.ExternalAffiliationHandler),
                    ("EXTSERVICE", faculty.event_types.info.ExternalServiceHandler),
                    ("FELLOW", faculty.event_types.awards.FellowshipEventHandler),
                    (
                        "GRANTAPP",
                        faculty.event_types.awards.GrantApplicationEventHandler,
                    ),
                    (
                        "NORM_TEACH",
                        faculty.event_types.teaching.NormalTeachingLoadHandler,
                    ),
                    ("LEAVE", faculty.event_types.career.OnLeaveEventHandler),
                    ("OTHER_NOTE", faculty.event_types.info.OtherEventHandler),
                    ("SALARY", faculty.event_types.career.SalaryBaseEventHandler),
                    ("RETIRE", faculty.event_types.career.RetirementEventHandler),
                    ("RESIGN", faculty.event_types.career.ResignationEventHandler),
                    (
                        "PROBATR",
                        faculty.event_types.career.ProbationaryReviewEventHandler,
                    ),
                    (
                        "TENPROAP",
                        faculty.event_types.career.TenurePromotionAssociateProfessorEventHandler,
                    ),
                    (
                        "ALTCA",
                        faculty.event_types.career.AlternateCareerPathEventHandler,
                    ),
                    (
                        "MODAPP",
                        faculty.event_types.career.ModifiedAppointmentEventHandler,
                    ),
                    ("ADDPAY", faculty.event_types.info.AddPayEventHandler),
                    (
                        "STIPEND",
                        faculty.event_types.career.SalaryModificationEventHandler,
                    ),
                    ("SPCL_DEAL", faculty.event_types.info.SpecialDealHandler),
                    ("STUDYLEAVE", faculty.event_types.career.StudyLeaveEventHandler),
                    ("TEACHING", faculty.event_types.awards.TeachingCreditEventHandler),
                    (
                        "TENUREAPP",
                        faculty.event_types.career.TenureApplicationEventHandler,
                    ),
                    (
                        "ACCRED",
                        faculty.event_types.career.AccreditationFlagEventHandler,
                    ),
                    (
                        "PROMOTION",
                        faculty.event_types.career.PromotionApplicationEventHandler,
                    ),
                    ("SALARYREV", faculty.event_types.career.SalaryReviewEventHandler),
                    (
                        "CONTRACTRV",
                        faculty.event_types.career.ContractReviewEventHandler,
                    ),
                ],
                help_text="The type of event that this memo applies to",
                max_length=10,
            ),
        ),
    ]
