# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import submission.models.base
import submission.models.gittag
import submission.models.office


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=5000, help_text='Maximum size of the archive file, in kB.'),
        ),
        migrations.AlterField(
            model_name='codecomponent',
            name='allowed',
            field=models.CharField(help_text='Accepted file extensions. [Contact system admins if you need more file types here.]', max_length=500, verbose_name='Allowed file types'),
        ),
        migrations.AlterField(
            model_name='codecomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=1000, help_text='Maximum size of the Code file, in kB.'),
        ),
        migrations.AlterField(
            model_name='codefilecomponent',
            name='filename',
            field=models.CharField(blank=True, help_text='Required filename for submitted files. Interpreted as specified in the filename type', max_length=500),
        ),
        migrations.AlterField(
            model_name='codefilecomponent',
            name='filename_type',
            field=models.CharField(choices=[('INS', "Filename must match, but uppercase and lowercase don't matter"), ('MAT', 'Filename must match exactly'), ('EXT', 'File Extension: the filename must end as specified'), ('REX', 'Regular Expression: the "filename" above must be a regular expression to match')], default='INS', help_text='How should your filename be interpreted?', max_length=3),
        ),
        migrations.AlterField(
            model_name='codefilecomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=500, help_text='Maximum size of the file, in kB.'),
        ),
        migrations.AlterField(
            model_name='gittagcomponent',
            name='check',
            field=models.BooleanField(default=False, help_text='Check that the repository and tag really exists? Implies that all submitted repos must be public http:// or https:// URLs.'),
        ),
        migrations.AlterField(
            model_name='gittagcomponent',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix that the URL *must* start with. (e.g. "git@github.com:" or "https://github.com", blank for none.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groupsubmission',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='groupsubmission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='imagecomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=1000, help_text='Maximum size of the image file, in kB.'),
        ),
        migrations.AlterField(
            model_name='officecomponent',
            name='allowed',
            field=submission.models.office.JSONFieldFlexible(help_text='Accepted file extensions.', max_length=500, verbose_name='Allowed types'),
        ),
        migrations.AlterField(
            model_name='officecomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=10000, help_text='Maximum size of the Office file, in kB.'),
        ),
        migrations.AlterField(
            model_name='pdfcomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=5000, help_text='Maximum size of the PDF file, in kB.'),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Activity'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(help_text='TA or instructor that will mark this submission', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In-Progress'), ('DON', 'Marked')], default='NEW', max_length=3),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Activity'),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='deleted',
            field=models.BooleanField(default=False, help_text="Component is invisible to students and can't be submitted if checked."),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='description',
            field=models.CharField(blank=True, help_text='Short explanation for this component.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The order of display for listing components.', null=True),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique_with=('activity',)),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='specified_filename',
            field=models.CharField(help_text='Specify a file name for this component.', max_length=200),
        ),
        migrations.AlterField(
            model_name='submissioncomponent',
            name='title',
            field=models.CharField(help_text='Name for this component (e.g. "Part 1" or "Programming Section")', max_length=100),
        ),
        migrations.AlterField(
            model_name='submittedarchive',
            name='archive',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Archive submission'),
        ),
        migrations.AlterField(
            model_name='submittedarchive',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.ArchiveComponent'),
        ),
        migrations.AlterField(
            model_name='submittedcode',
            name='code',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Code submission'),
        ),
        migrations.AlterField(
            model_name='submittedcode',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.CodeComponent'),
        ),
        migrations.AlterField(
            model_name='submittedcodefile',
            name='code',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Code submission'),
        ),
        migrations.AlterField(
            model_name='submittedcodefile',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.CodefileComponent'),
        ),
        migrations.AlterField(
            model_name='submittedcomponent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.Submission'),
        ),
        migrations.AlterField(
            model_name='submittedgittag',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.GitTagComponent'),
        ),
        migrations.AlterField(
            model_name='submittedgittag',
            name='tag',
            field=models.CharField(help_text='The tag you\'re submitting: created like "git tag submitted_code; git push origin --tags"', max_length=200, verbose_name='Tag name'),
        ),
        migrations.AlterField(
            model_name='submittedgittag',
            name='url',
            field=submission.models.gittag.GitURLField(help_text='Clone URL for your repository, like "https://server/user/repo.git" or "git@server:user/repo.git".', max_length=500, verbose_name='Repository URL'),
        ),
        migrations.AlterField(
            model_name='submittedimage',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.ImageComponent'),
        ),
        migrations.AlterField(
            model_name='submittedimage',
            name='image',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Image submission'),
        ),
        migrations.AlterField(
            model_name='submittedoffice',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.OfficeComponent'),
        ),
        migrations.AlterField(
            model_name='submittedoffice',
            name='office',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Office document submission'),
        ),
        migrations.AlterField(
            model_name='submittedpdf',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.PDFComponent'),
        ),
        migrations.AlterField(
            model_name='submittedpdf',
            name='pdf',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='PDF submission'),
        ),
        migrations.AlterField(
            model_name='submittedtext',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.TextComponent'),
        ),
        migrations.AlterField(
            model_name='submittedurl',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.URLComponent'),
        ),
        migrations.AlterField(
            model_name='submittedurl',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL submission'),
        ),
        migrations.AlterField(
            model_name='submittedword',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.WordComponent'),
        ),
        migrations.AlterField(
            model_name='submittedword',
            name='word',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Word document submission'),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=10, help_text='Maximum length, in kB.'),
        ),
        migrations.AlterField(
            model_name='urlcomponent',
            name='check',
            field=models.BooleanField(default=False, help_text='Check that the page really exists?  Will reject missing or password-protected URLs.'),
        ),
        migrations.AlterField(
            model_name='urlcomponent',
            name='prefix',
            field=models.CharField(blank=True, help_text='Prefix that the URL *must* start with. (e.g. "http://server.com/course/", blank for none.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordcomponent',
            name='max_size',
            field=submission.models.base.FileSizeField(default=10000, help_text='Maximum size of the Word/OpenDoc file, in kB.'),
        ),
    ]
