# Generated by Django 2.2.3 on 2019-09-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_add_livecode'),
        ('submission', '0006_add_similarity'),
    ]

    operations = [
    ]
