# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import submission.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecodecomponent',
            name='language',
            field=models.CharField(choices=[('apl', 'APL'), ('asn.1', 'ASN.1'), ('clike', 'C, C++, C#'), ('clike', 'Ceylon'), ('clojure', 'Clojure'), ('cmake', 'CMake'), ('cobol', 'COBOL'), ('coffeescript', 'CoffeeScript'), ('commonlisp', 'Common Lisp'), ('crystal', 'Crystal'), ('css', 'CSS'), ('cypher', 'Cypher'), ('python', 'Cython'), ('d', 'D'), ('dart', 'Dart'), ('diff', 'diff'), ('django', 'Django template'), ('dockerfile', 'Dockerfile'), ('dtd', 'DTD'), ('dylan', 'Dylan'), ('ebnf', 'EBNF'), ('ecl', 'ECL'), ('eiffel', 'Eiffel'), ('elm', 'Elm'), ('erlang', 'Erlang'), ('mllike', 'F#'), ('factor', 'Factor'), ('fcl', 'FCL'), ('forth', 'Forth'), ('fortran', 'Fortran'), ('gas', 'Gas'), ('gherkin', 'Gherkin'), ('go', 'Go'), ('groovy', 'Groovy'), ('haml', 'HAML'), ('handlebars', 'Handlebars'), ('haskell', 'Haskell'), ('haskell-literate', 'Haskell, Literate'), ('haxe', 'Haxe'), ('http', 'HTTP'), ('idl', 'IDL'), ('clike', 'Java'), ('javascript', 'JavaScript'), ('jinja2', 'Jinja2'), ('jsx', 'JSX'), ('julia', 'Julia'), ('clike', 'Kotlin'), ('livescript', 'LiveScript'), ('lua', 'Lua'), ('markdown', 'Markdown'), ('gfm', 'Markdown, GitHub-flavour'), ('mathematica', 'Mathematica'), ('modelica', 'Modelica'), ('ntriples', 'N-Triples/N-Quads'), ('nginx', 'Nginx'), ('nsis', 'NSIS'), ('clike', 'Objective C'), ('mllike', 'OCaml'), ('octave', 'Octave'), ('oz', 'Oz'), ('pascal', 'Pascal'), ('pegjs', 'PEG.js'), ('perl', 'Perl'), ('php', 'PHP'), ('pig', 'Pig Latin'), ('plain-text', 'Plain text (no syntax highlighting)'), ('powershell', 'PowerShell'), ('protobuf', 'ProtoBuf'), ('pug', 'Pug'), ('puppet', 'Puppet'), ('python', 'Python'), ('q', 'Q'), ('r', 'R'), ('rst', 'reStructuredText'), ('rpm', 'RPM'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sas', 'SAS'), ('sass', 'Sass'), ('scheme', 'Scheme'), ('shell', 'Shell'), ('sieve', 'Sieve'), ('slim', 'Slim'), ('smalltalk', 'Smalltalk'), ('smarty', 'Smarty'), ('solr', 'Solr'), ('soy', 'Soy'), ('sparql', 'SPARQL'), ('sql', 'SQL'), ('clike', 'Squirrel'), ('stex', 'sTeX, LaTeX'), ('stylus', 'Stylus'), ('swift', 'Swift'), ('tcl', 'Tcl'), ('textile', 'Textile'), ('tiddlywiki', 'Tiddlywiki'), ('tiki', 'Tiki wiki'), ('toml', 'TOML'), ('tornado', 'Tornado template'), ('troff', 'troff'), ('turtle', 'Turtle'), ('twig', 'Twig'), ('vb', 'VB.NET'), ('vbscript', 'VBScript'), ('velocity', 'Velocity'), ('verilog', 'Verilog/SystemVerilog'), ('vhdl', 'VHDL'), ('vue', 'Vue.js app'), ('webidl', 'Web IDL'), ('xml', 'XML/HTML'), ('xquery', 'XQuery'), ('yacas', 'Yacas'), ('yaml', 'YAML'), ('z80', 'Z80')], help_text='Syntax highlighting that will be used in the entry box.', max_length=50, verbose_name='Programming Language'),
        ),
        migrations.AlterField(
            model_name='similaritydata',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.similarity_upload_path),
        ),
        migrations.AlterField(
            model_name='submittedarchive',
            name='archive',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Archive submission'),
        ),
        migrations.AlterField(
            model_name='submittedcode',
            name='code',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Code submission'),
        ),
        migrations.AlterField(
            model_name='submittedcodefile',
            name='code',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Code submission'),
        ),
        migrations.AlterField(
            model_name='submittedimage',
            name='image',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Image submission'),
        ),
        migrations.AlterField(
            model_name='submittedoffice',
            name='office',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Office document submission'),
        ),
        migrations.AlterField(
            model_name='submittedpdf',
            name='pdf',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='PDF submission'),
        ),
        migrations.AlterField(
            model_name='submittedword',
            name='word',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=submission.models.base.submission_upload_path, verbose_name='Word document submission'),
        ),
    ]
