# Generated by Django 4.2.23 on 2025-08-30 17:19

import django.core.files.storage
from django.db import migrations, models
import submission.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0007_merge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="urlcomponent",
            old_name="check",
            new_name="check_exists",
        ),
        migrations.RemoveField(
            model_name="gittagcomponent",
            name="check",
        ),
    ]
