# Generated by Django 4.2.23 on 2025-09-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_remove_rename_check'),
        ('submission', '0008_trivial_migration_updates'),
    ]

    operations = [
    ]
