# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import visas.models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0006_add_unit_to_visas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expiry of the visa (if known)', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='start_date',
            field=models.DateField(default=visas.models.timezone_today, help_text='First day of visa validity', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='status',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Work', 'Work Visa'), ('Perm Resid', 'Permanent Resident'), ('Student', 'Student Visa'), ('Diplomat', 'Diplomat'), ('Min Permit', "Minister's Permit"), ('Other', 'Other Visa'), ('Visitor', "Visitor's Visa"), ('Unknown', 'Not Known'), ('New CDN', "'New' Canadian citizen"), ('Conv Refug', 'Convention Refugee'), ('Refugee', 'Refugee'), ('Unknown', 'Non-Canadian, Status Unknown'), ('No Visa St', 'Non-Canadian, No Visa Status'), ('Live-in Ca', 'Live-in Caregiver')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visa',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='visadocumentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=visas.models.visa_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='visadocumentattachment',
            name='created_by',
            field=models.ForeignKey(help_text='Document attachment created by.', on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='visadocumentattachment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('visa',)),
        ),
        migrations.AlterField(
            model_name='visadocumentattachment',
            name='visa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='visas.Visa'),
        ),
    ]
