# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import visas.models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0007_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visadocumentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=visas.models.visa_attachment_upload_to),
        ),
    ]
