/nginx_logs/*.log {
  daily
  missingok
  rotate 31
  dateext
  dateformat -%Y%m%d-%H%M%S
  compress
  delaycompress
  missingok
  sharedscripts
  postrotate 
    pkill -USR1 nginx  # Container must be deployed with "--pid=host" for this to work.
  endscript
}