from django.conf.urls import url
from courselib.urlparts import LETTER_TEMPLATE_SLUG, GRAD_SLUG, LETTER_TEMPLATE_ID, LETTER_SLUG

grad_patterns = [ # prefix /grad/
    url(r'^$', 'grad.views.index', name='index'),
    #url(r'^import$', 'grad.views.import_applic', name='import_applic'),
    url(r'^progress_reports', 'grad.views.progress_reports', name='progress_reports'),
    url(r'^search$', 'grad.views.search', name='search'),
    url(r'^search/save$', 'grad.views.save_search', name='save_search'),
    url(r'^search/delete$', 'grad.views.delete_savedsearch', name='delete_savedsearch'),
    url(r'^qs', 'grad.views.quick_search', name='quick_search'),

    url(r'^program/new$', 'grad.views.new_program', name='new_program'),
    url(r'^program/$', 'grad.views.programs', name='programs'),
    url(r'^requirement/$', 'grad.views.requirements', name='requirements'),
    url(r'^requirement/new$', 'grad.views.new_requirement', name='new_requirement'),

    url(r'^letterTemplates/$', 'grad.views.letter_templates', name='letter_templates'),
    url(r'^letterTemplates/new', 'grad.views.new_letter_template', name='new_letter_template'),
    url(r'^letterTemplates/' + LETTER_TEMPLATE_SLUG + '/manage', 'grad.views.manage_letter_template', name='manage_letter_template'),
    url(r'^promises/$', 'grad.views.all_promises', name='all_promises'),
    url(r'^promises/(?P<semester_name>\d{4})$', 'grad.views.all_promises', name='all_promises'),
    url(r'^funding/$', 'grad.views.funding_report', name='funding_report'),
    url(r'^funding/(?P<semester_name>\d{4})$', 'grad.views.funding_report', name='funding_report'),

    url(r'^' + GRAD_SLUG + '/$', 'grad.views.view', name='view'),
    url(r'^' + GRAD_SLUG + '/moreinfo$', 'grad.views.grad_more_info', name='grad_more_info'),
    url(r'^' + GRAD_SLUG + '/general$', 'grad.views.manage_general', name='manage_general'),
    url(r'^' + GRAD_SLUG + '/program', 'grad.views.manage_program', name='manage_program'),
    url(r'^' + GRAD_SLUG + '/start_end', 'grad.views.manage_start_end_semesters', name='manage_start_end_semesters'),
    url(r'^' + GRAD_SLUG + '/defence', 'grad.views.manage_defence', name='manage_defence'),
    url(r'^' + GRAD_SLUG + '/form', 'grad.views.get_form', name='get_form'),
    url(r'^' + GRAD_SLUG + '/supervisors$', 'grad.views.manage_supervisors', name='manage_supervisors'),
    url(r'^' + GRAD_SLUG + '/supervisors/(?P<sup_id>\d+)/remove$', 'grad.views.remove_supervisor', name='remove_supervisor'),
    url(r'^' + GRAD_SLUG + '/status$', 'grad.views.manage_status', name='manage_status'),
    url(r'^' + GRAD_SLUG + '/status/(?P<s_id>\d+)/remove$', 'grad.views.remove_status', name='remove_status'),
    url(r'^' + GRAD_SLUG + '/requirements$', 'grad.views.manage_requirements', name='manage_requirements'),
    url(r'^' + GRAD_SLUG + '/requirements/(?P<cr_id>\d+)/remove$', 'grad.views.remove_completedrequirement', name='remove_completedrequirement'),
    url(r'^' + GRAD_SLUG + '/otherfunding$', 'grad.views.manage_otherfunding', name='manage_otherfunding'),
    url(r'^' + GRAD_SLUG + '/otherfunding/(?P<o_id>\d+)/remove$', 'grad.views.remove_otherfunding', name='remove_otherfunding'),
    url(r'^' + GRAD_SLUG + '/financial$', 'grad.views.financials', name='financials'),
    url(r'^' + GRAD_SLUG + '/financial-(?P<style>\w+)$', 'grad.views.financials', name='financials'),
    url(r'^' + GRAD_SLUG + '/financialcomments$', 'grad.views.manage_financialcomments', name='manage_financialcomments'),
    url(r'^' + GRAD_SLUG + '/financialcomments/(?P<f_id>\d+)/remove$', 'grad.views.remove_financialcomment', name='remove_financialcomment'),
    url(r'^' + GRAD_SLUG + '/promises$', 'grad.views.manage_promises', name='manage_promises'),
    url(r'^' + GRAD_SLUG + '/promises/(?P<p_id>\d+)/remove$', 'grad.views.remove_promise', name='remove_promise'),
    url(r'^' + GRAD_SLUG + '/progress_reports$', 'grad.views.manage_progress', name='manage_progress'),
    url(r'^' + GRAD_SLUG + '/progress_reports/(?P<p_id>\d+)/remove$', 'grad.views.remove_progress', name='remove_progress'),
    url(r'^' + GRAD_SLUG + '/documents$', 'grad.views.manage_documents', name='manage_documents'),
    url(r'^' + GRAD_SLUG + '/documents/(?P<d_id>\d+)/remove$', 'grad.views.remove_document', name='remove_document'),
    url(r'^' + GRAD_SLUG + '/documents/(?P<d_id>\d+)/download$', 'grad.views.download_file', name='download_file'),
    url(r'^' + GRAD_SLUG + '/scholarship$', 'grad.views.manage_scholarships', name='manage_scholarships'),
    url(r'^' + GRAD_SLUG + '/scholarship/(?P<s_id>\d+)/remove$', 'grad.views.remove_scholarship', name='remove_scholarship'),
    url(r'^' + GRAD_SLUG + '/letters$', 'grad.views.manage_letters', name='manage_letters'),
    url(r'^' + GRAD_SLUG + '/letters/' + LETTER_TEMPLATE_SLUG + '/new$', 'grad.views.new_letter', name='new_letter'),
    url(r'^' + GRAD_SLUG + '/letters/_get_text/' + LETTER_TEMPLATE_ID + '$', 'grad.views.get_letter_text', name='get_letter_text'),
    url(r'^' + GRAD_SLUG + '/letters/' + LETTER_SLUG + '$', 'grad.views.get_letter', name='get_letter'),
    url(r'^' + GRAD_SLUG + '/letters/' + LETTER_SLUG + '/view$', 'grad.views.view_letter', name='view_letter'),
    url(r'^' + GRAD_SLUG + '/letters/' + LETTER_SLUG + '/copy', 'grad.views.copy_letter', name='copy_letter'),
    url(r'^get_addresses$', 'grad.views.get_addresses', name='get_addresses'),
    url(r'^scholarship_types$', 'grad.views.manage_scholarshipType', name='manage_scholarshipType'),
    url(r'^financial_summary$', 'grad.views.student_financials', name='student_financials'),
    #url(r'^new', 'grad.views.new', name='new'),
    url(r'^found', 'grad.views.not_found', name='not_found'),
]
