# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_change_waiver_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachevent',
            name='registration_cap',
            field=models.PositiveIntegerField(blank=True, help_text=b'If you set a registration cap, people will not be allowed to register after you have reached this many registrations marked as attending.', null=True),
        ),
        migrations.AddField(
            model_name='outreachevent',
            name='registration_email_text',
            field=models.TextField(blank=True, help_text=b'If you fill this in, this will be sent as an email to all all new registrants as a registration confirmation.', null=True),
        ),
        migrations.AddField(
            model_name='outreacheventregistration',
            name='birthdate',
            field=models.DateField(default=datetime.date(1800, 1, 1), verbose_name=b'Participant Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outreacheventregistration',
            name='school',
            field=models.CharField(default='N/A', max_length=200, verbose_name=b'Participant School'),
            preserve_default=False,
        ),
    ]
