# Generated by Django 2.0.3 on 2018-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_add_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachevent',
            name='show_dietary_question',
            field=models.BooleanField(default=True, help_text="If this box is checked, the registration forms will show the dietary restrictions question.  Otherwise, it'll be omitted."),
        ),
        migrations.AlterField(
            model_name='outreachevent',
            name='enable_waitlist',
            field=models.BooleanField(default=False, help_text='If this box is checked and you have a registration cap which has been met, people will still be able to register but will be marked as not attending and waitlisted.'),
        ),
    ]
