# Generated by Django 2.0.9 on 2019-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_add_option_to_hide_dietary_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreacheventregistration',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='outreacheventregistration',
            name='secondary_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Secondary Emergency Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreacheventregistration',
            name='secondary_phone',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Secondary Emergency Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outreacheventregistration',
            name='notes',
            field=models.CharField(blank=True, help_text='Describe any allergies, dietary restrictions, or medical conditions. Please include information on severity and whether an Epipen is required. Students requiring an Epipen must carry it on their person for the entire event and identify themselves to staff at registration.', max_length=400, null=True, verbose_name='Allergies/Dietary Restrictions'),
        ),
        migrations.AlterField(
            model_name='outreacheventregistration',
            name='parent_name',
            field=models.CharField(max_length=100, verbose_name='Parent/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='outreacheventregistration',
            name='parent_phone',
            field=models.CharField(max_length=15, verbose_name='Parent/Guardian Phone'),
        ),
    ]
