# Generated by Django 4.2.23 on 2026-01-19 16:32

import courselib.uuid
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("outreach", "0013_remove_score_add_private_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreacheventregistration",
            name="uuid",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
