# Generated by Django 5.2.17 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="can_read",
            field=models.CharField(
                choices=[
                    ("NONE", "nobody"),
                    ("INST", "instructor"),
                    ("STAF", "instructor and TAs"),
                    ("STUD", "students, instructor and TAs"),
                    ("LOG", "any logged in SFU user"),
                    ("ALL", "anybody: publicly visible"),
                ],
                default="ALL",
                help_text="Who should be able to view this page?",
                max_length=4,
            ),
        ),
    ]
