# Generated by Django 2.0.3 on 2018-05-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0021_new_roles'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('ident', models.CharField(db_index=True, max_length=255, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coredata.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('PERS', 'Me personally'), ('INST', 'Me when teaching a specific course'), ('ROLE', 'All people with role')], max_length=4, verbose_name='Who gets reminded?'),
        ),
        migrations.AddField(
            model_name='remindermessage',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.Reminder'),
        ),
    ]
