# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  # config.vm.boot_mode = :gui
  config.vm.network "forwarded_port", guest:8000, host:8000
  config.vm.synced_folder "../..", "/home/vagrant/courses",
      id: "coursys-project",
      owner: "vagrant",
      group: "www-data",
      mount_options: ["dmode=777,fmode=777"]

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    # speed up boot: https://bugs.launchpad.net/cloud-images/+bug/1829625
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "../chef/cookbooks"
     chef.add_recipe "apt"
     chef.add_recipe "coursys"
     chef.arguments = "--chef-license accept"
  end

end
