# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.boot_mode = :gui
  config.vm.network "forwarded_port", guest:8000, host:8000
  config.vm.synced_folder "../..", "/home/vagrant/courses",
      id: "coursys-project",
      owner: "ubuntu",
      group: "www-data",
      mount_options: ["dmode=777,fmode=777"]

  config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--uartmode1", "disconnected"] # speed up boot https://bugs.launchpad.net/cloud-images/+bug/1627844
  end

  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = "../chef/cookbooks"
     chef.add_recipe "apt"
     chef.add_recipe "coursys"
     chef.version = "14.12.9"
  end

end
