# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='comment',
            field=models.TextField(help_text='Comment from the user (if available)', null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='description',
            field=models.CharField(help_text='Description from the system of the change made', max_length=255),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='userid',
            field=models.CharField(db_index=True, help_text='Userid who made the change', max_length=8),
        ),
    ]
