# Generated by Django 3.2.23 on 2023-11-23 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(help_text='Time of the *start* of this event.')),
                ('duration', models.DurationField()),
                ('data', models.JSONField()),
                ('task', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(help_text='Time of the *start* of this event.')),
                ('duration', models.DurationField()),
                ('data', models.JSONField()),
                ('username', models.CharField(db_index=True, max_length=32, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['-time'],
                'abstract': False,
            },
        ),
    ]
