# Generated by Django 3.2.25 on 2025-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_celerytasklog_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytasklog',
            name='duration',
            field=models.DurationField(help_text='Time taken for this event.'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='duration',
            field=models.DurationField(help_text='Time taken for this event.'),
        ),
    ]
