# Generated by Django 3.2.25 on 2025-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_trivial_migration_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytasklog',
            name='time',
            field=models.DateTimeField(db_index=True, help_text='Time of the *start* of this event.'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='time',
            field=models.DateTimeField(db_index=True, help_text='Time of the *start* of this event.'),
        ),
    ]
