# Generated by Django 4.2.30 on 2026-05-12 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0005_index_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringDataLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, help_text="Time of the *start* of this event."
                    ),
                ),
                (
                    "duration",
                    models.DurationField(help_text="Time taken for this event."),
                ),
                ("data", models.JSONField()),
                ("metric", models.CharField(db_index=True, max_length=255)),
                ("value", models.FloatField(verbose_name="value")),
            ],
            options={
                "ordering": ["-time"],
                "abstract": False,
            },
        ),
    ]
