# Generated by Django 4.2.23 on 2026-01-19 16:32

import courselib.uuid
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0005_index_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerytasklog",
            name="id",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid1, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="id",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid1, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
