# Generated by Django 4.2.30 on 2026-07-06 20:17

import courselib.uuid
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0006_monitoringdatalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerytasklog",
            name="id",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid1, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="monitoringdatalog",
            name="id",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid1, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="id",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid1, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
