# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_comment_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(help_text='Activity due date', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the activity.', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='position',
            field=models.PositiveSmallIntegerField(help_text='The order of displaying course activities.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_name',
            field=models.CharField(db_index=True, help_text='Short-form name of the activity.', max_length=15),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='String that identifies this activity within the course offering', populate_from='autoslug', unique_with=('offering',)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('RLS', 'grades released'), ('URLS', 'grades not released to students'), ('INVI', 'activity not visible to students')], help_text='Activity status.', max_length=4),
        ),
        migrations.AlterField(
            model_name='calletteractivity',
            name='exam_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cal_exam_activity', to='grades.Activity'),
        ),
        migrations.AlterField(
            model_name='calletteractivity',
            name='letter_cutoffs',
            field=models.CharField(default='[95, 90, 85, 80, 75, 70, 65, 60, 55, 50]', help_text='parsed formula to calculate final letter grade', max_length=500),
        ),
        migrations.AlterField(
            model_name='calletteractivity',
            name='numeric_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeric_source', to='grades.NumericActivity'),
        ),
        migrations.AlterField(
            model_name='calnumericactivity',
            name='formula',
            field=models.TextField(default='[[activitytotal]]', help_text='parsed formula to calculate final numeric grade'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Activity'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='activity_status',
            field=models.CharField(choices=[('RLS', 'grades released'), ('URLS', 'grades not released to students'), ('INVI', 'activity not visible to students')], help_text='Activity status when grade was entered.', max_length=4),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='grade_flag',
            field=models.CharField(choices=[('NOGR', 'no grade'), ('GRAD', 'graded'), ('CALC', 'calculated'), ('EXCU', 'excused'), ('DISH', 'academic dishonesty')], help_text='Status of the grade', max_length=4),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='group',
            field=models.ForeignKey(help_text='If this was a mark for a group, the group.', null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='letter_grade',
            field=models.CharField(choices=[('A+', 'A+ (Excellent performance)'), ('A', 'A (Excellent performance)'), ('A-', 'A- (Excellent performance)'), ('B+', 'B+ (Good performance)'), ('B', 'B (Good performance)'), ('B-', 'B- (Good performance)'), ('C+', 'C+ (Satisfactory performance)'), ('C', 'C (Satisfactory performance)'), ('C-', 'C- (Marginal performance)'), ('D', 'D (Marginal performance)'), ('F', 'F (Fail. Unsatisfactory Performance)'), ('N', 'N (Did not write exam or did not complete course)'), ('P', 'P (Satisfactory performance or better (pass, ungraded))'), ('DE', 'DE (Deferred grade)'), ('GN', 'GN (Grade not reported)'), ('IP', 'IP (In progress)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='mark',
            field=models.ForeignKey(help_text='The ActivityMark object this grade came from, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, to='marking.ActivityMark'),
        ),
        migrations.AlterField(
            model_name='gradehistory',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.LetterActivity'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='flag',
            field=models.CharField(choices=[('NOGR', 'no grade'), ('GRAD', 'graded'), ('CALC', 'calculated'), ('EXCU', 'excused'), ('DISH', 'academic dishonesty')], default='NOGR', help_text='Status of the grade', max_length=4),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='letter_grade',
            field=models.CharField(choices=[('A+', 'A+ (Excellent performance)'), ('A', 'A (Excellent performance)'), ('A-', 'A- (Excellent performance)'), ('B+', 'B+ (Good performance)'), ('B', 'B (Good performance)'), ('B-', 'B- (Good performance)'), ('C+', 'C+ (Satisfactory performance)'), ('C', 'C (Satisfactory performance)'), ('C-', 'C- (Marginal performance)'), ('D', 'D (Marginal performance)'), ('F', 'F (Fail. Unsatisfactory Performance)'), ('N', 'N (Did not write exam or did not complete course)'), ('P', 'P (Satisfactory performance or better (pass, ungraded))'), ('DE', 'DE (Deferred grade)'), ('GN', 'GN (Grade not reported)'), ('IP', 'IP (In progress)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='numericgrade',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.NumericActivity'),
        ),
        migrations.AlterField(
            model_name='numericgrade',
            name='flag',
            field=models.CharField(choices=[('NOGR', 'no grade'), ('GRAD', 'graded'), ('CALC', 'calculated'), ('EXCU', 'excused'), ('DISH', 'academic dishonesty')], default='NOGR', help_text='Status of the grade', max_length=4),
        ),
        migrations.AlterField(
            model_name='numericgrade',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
    ]
