# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tacontracts', '0007_add_course_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedescription',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description',
            field=models.CharField(help_text="Description of the work for a course, as it will appear on the contract. (e.g. 'Office/marking')", max_length=60),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='description_unit', to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='emailreceipt',
            name='content',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='dashboard.NewsItem'),
        ),
        migrations.AlterField(
            model_name='emailreceipt',
            name='contract',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='email_receipt', to='tacontracts.TAContract'),
        ),
        migrations.AlterField(
            model_name='hiringsemester',
            name='config',
            field=courselib.json_fields.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='hiringsemester',
            name='payperiods',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='During the contract, how many bi-weekly pay periods?'),
        ),
        migrations.AlterField(
            model_name='hiringsemester',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='hiringsemester',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ra.Account'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='bu_lab_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.17'), max_digits=8, verbose_name='Bonus BUs awarded to a course with a lab'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='code',
            field=models.CharField(help_text="Category Choice Code - for example 'GTA2'", max_length=5),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='hiring_semester',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='tacontracts.HiringSemester'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='holiday_hours_per_bu',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.1'), max_digits=4, verbose_name='Holiday hours per BU'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='hours_per_bu',
            field=models.DecimalField(decimal_places=2, default=Decimal('42'), max_digits=6, verbose_name='Hours per BU'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='pay_per_bu',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Default pay, per base unit'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='scholarship_per_bu',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Scholarship pay, per base unit'),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='tacategory',
            name='title',
            field=models.CharField(help_text="Category Choice Title - for example 'PhD'", max_length=50),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='accepted_by_student',
            field=models.BooleanField(default=False, help_text='Has the student accepted the contract?'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='appointment',
            field=models.CharField(choices=[('INIT', 'Initial appointment to this position'), ('REAP', 'Reappointment to same position or revision to appointment')], default='INIT', max_length=4),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='tacontracts.TACategory'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='payperiods',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='During the contract, how many bi-weekly pay periods?'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='sin',
            field=models.CharField(help_text='Social Insurance Number - 000000000 if unknown', max_length=30, verbose_name='SIN'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='status',
            field=models.CharField(choices=[('NEW', 'Draft'), ('SGN', 'Signed'), ('CAN', 'Cancelled')], default='NEW', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='visa_verified',
            field=models.BooleanField(default=False, help_text="I have verified this TA's visa information"),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='bu',
            field=models.DecimalField(decimal_places=2, help_text='The number of Base Units for this course.', max_digits=4, verbose_name='BUs'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='contract',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='tacontracts.TAContract'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tacontracts.CourseDescription'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='labtut',
            field=models.BooleanField(default=False, help_text='Does this course have a lab or tutorial?', verbose_name='Lab/Tutorial?'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='member',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tacourse', to='coredata.Member'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug'),
        ),
    ]
