# Generated by Django 2.0.3 on 2018-04-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tacontracts', '0008_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreceipt',
            name='content',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.NewsItem'),
        ),
    ]
