# Generated by Django 2.0.3 on 2018-09-28 14:12

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tacontracts.models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0021_new_roles'),
        ('tacontracts', '0009_delete_emailreceipt_on_newsitem_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAContractAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('contract',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=tacontracts.models.tacontracts_attachment_upload_to)),
                ('mediatype', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tacontracts.TAContract')),
                ('created_by', models.ForeignKey(help_text='Document attachment created by.', on_delete=django.db.models.deletion.PROTECT, to='coredata.Person')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='tacontractattachment',
            unique_together={('contract', 'slug')},
        ),
    ]
