# Generated by Django 2.2.15 on 2021-01-20 14:21

import datetime
import django.core.files.storage
from django.db import migrations, models
import tacontracts.models
sentinel_date = datetime.date(1970, 1, 1)


class Migration(migrations.Migration):

    dependencies = [
        ('tacontracts', '0010_add_attachments_to_tacontracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringsemester',
            name='appointment_end',
            field=models.DateField(default=sentinel_date),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiringsemester',
            name='appointment_start',
            field=models.DateField(default=sentinel_date),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tacontractattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=tacontracts.models.tacontracts_attachment_upload_to),
        ),
    ]
