# Generated by Django 2.2.15 on 2021-01-20 14:23

from django.db import migrations
import datetime
sentinel_date = datetime.date(1970, 1, 1)


def fill_start_end(apps, schema_editor):
    HiringSemester = apps.get_model('tacontracts', 'HiringSemester')

    for hs in HiringSemester.objects.filter(appointment_start=sentinel_date).select_related('semester'):
        hs.appointment_start = hs.semester.start
        hs.save()

    for hs in HiringSemester.objects.filter(appointment_end=sentinel_date).select_related('semester'):
        hs.appointment_end = hs.semester.end
        hs.save()


def ignore(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tacontracts', '0011_add_start_end'),
    ]

    operations = [
        migrations.RunPython(fill_start_end, reverse_code=ignore),
    ]
