# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import tacontracts.models


class Migration(migrations.Migration):

    dependencies = [
        ('tacontracts', '0012_fill_start_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacontract',
            name='appointment',
            field=models.CharField(choices=[('INIT', 'Initial appointment to this position'), ('REAP', 'Reappointment to same position or revision to appointment')], default='REAP', max_length=4),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='comments',
            field=models.TextField(blank=True, max_length=625),
        ),
        migrations.AlterField(
            model_name='tacontractattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=tacontracts.models.tacontracts_attachment_upload_to),
        ),
    ]
