# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 15:12


import courselib.json_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fix_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(help_text=b'Main story content'),
        ),
    ]
