# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import courselib.json_fields
import dashboard.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_newsite_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(help_text='Main story content'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='read',
            field=models.BooleanField(default=False, help_text='The user has marked the story read'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source_app',
            field=models.CharField(help_text='Application that created the story', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(help_text='Story title (plain text)', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(blank=True, help_text='absolute URL for the item: starts with "http://" or "/"', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='sig',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=dashboard.models._sig_upload_to),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='value',
            field=courselib.json_fields.JSONField(default=dict),
        ),
    ]
