# Generated by Django 3.2.25 on 2025-08-27 17:01

import dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='sig',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=dashboard.models._sig_upload_to),
        ),
    ]
