# make sure we notice restarted app container, per https://stackoverflow.com/questions/35744650/docker-network-nginx-resolver
resolver 127.0.0.11;

upstream backend {
        server app:8000;
}

# server{} entries appended here by nginx-configure-host.sh