# make sure we notice restarted app container, per
# https://stackoverflow.com/questions/35744650/docker-network-nginx-resolver
# https://serverfault.com/questions/722438/nginx-refresh-upstream-server-ip
resolver 127.0.0.11 valid=10s;

upstream backend {
        zone upstream_dynamic 64k;
        server app:8000 resolve;
}

# log the IP address specified by the load balancer
real_ip_header    X-Forwarded-For;
set_real_ip_from 142.58.0.0/16;  # in prod, only the load balancer can possibly send requests, so trust broadly

# server{} entries appended here by nginx-configure-host.sh
