server {
        # redirect any other requests to canonical domain (shouldn't happen except for suspicious requests)
        server_name _;
        listen 80 default_server;

        access_log /nginx_logs/default-http.access.log main;
        error_log /nginx_logs/default-http.error.log warn;

        return 301 USER_PROTOCOL://CANONICAL_NAME:USER_PORT$request_uri;
}
