server {
        server_name DOMAIN_NAME;
        listen 80;
        access_log /nginx_logs/DOMAIN_NAME-http.access.log main;
        error_log /nginx_logs/DOMAIN_NAME-http.error.log warn;

        return 301 https://CANONICAL_NAME$request_uri;
}