server {
        server_name DOMAIN_NAME;
        listen 80;
        access_log /nginx-logs/DOMAIN_NAME-http.access.log main;
        error_log /nginx-logs/DOMAIN_NAME-http.error.log warn;

        include /etc/nginx/common.conf;
}