# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 14:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_autoslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseattachment',
            name='name',
            field=models.CharField(blank=True, help_text=b'Identifying name for the attachment', max_length=150, null=True, verbose_name=b'Name'),
        ),
    ]
