# Generated by Django 2.2.22 on 2021-08-18 14:17

import discipline.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0005_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecasebase',
            name='central_note',
            field=models.TextField(blank=True, help_text='Additional notes about the case status (visible to student and instructor, <a href="javascript:textile_popup()">Textile markup</a> and <a href="javascript:substitution_popup()">case substitutions</a> allowed)', null=True, verbose_name='Student Services Note'),
        ),
        migrations.AddField(
            model_name='disciplinecasebase',
            name='central_note_date',
            field=models.DateField(blank=True, help_text='Last update to the Student Services note.', null=True, verbose_name='Student Services Note Date'),
        ),
        migrations.AlterField(
            model_name='caseattachment',
            name='attachment',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=discipline.models._disc_upload_to, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='disciplinetemplate',
            name='field',
            field=models.CharField(choices=[('notes', 'private notes'), ('notes_public', 'public notes'), ('contact_email_text', 'initial contact email'), ('response', 'student response details'), ('meeting_summary', 'student meeting/email summary'), ('meeting_notes', 'student meeting/email notes'), ('facts', 'facts of the case'), ('penalty_reason', 'penalty rationale')], help_text='The field this template applies to', max_length=30, verbose_name='Field'),
        ),
    ]
