# Generated by Django 2.2.28 on 2022-06-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0007_disciplinecasebase_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='contacted',
            field=models.CharField(choices=[('NONE', 'Not yet contacted'), ('MAIL', 'Student emailed through this system'), ('OTHR', 'Student contacted (outside of this system)')], default='NONE', help_text='Has the student been informed of the case?', max_length=4, verbose_name='Student Contacted?'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='penalty',
            field=models.CharField(default='WAIT', help_text='Penalty assigned by the instructor for this case.', max_length=20, verbose_name='Instructor Penalty'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='response',
            field=models.CharField(choices=[('WAIT', 'Waiting for response'), ('NONE', 'No response from student'), ('DECL', 'Student declined to meet'), ('MAIL', 'Student sent statement by email'), ('MET', 'Met with student')], default='WAIT', help_text='Has the student responded to the initial contact?', max_length=4, verbose_name='Student Response'),
        ),
    ]
