# Generated by Django 3.2.25 on 2025-08-27 17:01

import discipline.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0008_longer_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseattachment',
            name='attachment',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=discipline.models._disc_upload_to, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='central_note',
            field=models.TextField(blank=True, help_text='Additional notes about the case status (visible to student and instructor)', null=True, verbose_name='Student Services Note'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='contact_email_text',
            field=models.TextField(blank=True, help_text='The initial email sent to the student regarding the case. Please also note the date of the email.', null=True, verbose_name='Contact Email Text'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='facts',
            field=models.TextField(blank=True, help_text="Summary of the facts of the case (included in letter).  This should be a summary of the case from the instructor's perspective.", null=True, verbose_name='Facts of the Case'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='Notes about the meeting/email with student (private notes).', null=True, verbose_name='Meeting/Email Notes'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='meeting_summary',
            field=models.TextField(blank=True, help_text='Summary of the meeting/email with student (included in letter).', null=True, verbose_name='Meeting/Email Summary'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the case (private notes).', null=True, verbose_name='Private Notes'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='notes_public',
            field=models.TextField(blank=True, help_text='Notes about the case (public notes).', null=True, verbose_name='Public Notes'),
        ),
        migrations.AlterField(
            model_name='disciplinecasebase',
            name='penalty_reason',
            field=models.TextField(blank=True, help_text='Rationale for assigned penalty, or notes/details concerning penalty.  Optional but recommended. (included in letter)', null=True, verbose_name='Penalty Rationale/Details'),
        ),
        migrations.AlterField(
            model_name='disciplinetemplate',
            name='text',
            field=models.TextField(help_text='The text for the template.  Templates can contain substitutions described below.', verbose_name='Text'),
        ),
    ]
