# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import marking.models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0006_activitycomponentmark_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycomponent',
            name='numeric_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.NumericActivity'),
        ),
        migrations.AlterField(
            model_name='activitycomponent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique_with=('numeric_activity',)),
        ),
        migrations.AlterField(
            model_name='activitycomponentmark',
            name='activity_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marking.ActivityComponent'),
        ),
        migrations.AlterField(
            model_name='activitycomponentmark',
            name='activity_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marking.ActivityMark'),
        ),
        migrations.AlterField(
            model_name='activitycomponentmark',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activitycomponentmark',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grades.NumericActivity'),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='created_by',
            field=models.CharField(help_text='Userid who gives the mark', max_length=8),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=marking.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='late_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage to deduct from the total due to late submission', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='mark_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Points to deduct for any special reasons (may be negative for bonus)', max_digits=8, null=True, verbose_name='Mark Penalty'),
        ),
        migrations.AlterField(
            model_name='activitymark',
            name='mark_adjustment_reason',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Mark Penalty Reason'),
        ),
        migrations.AlterField(
            model_name='activitymark_lettergrade',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grades.LetterActivity'),
        ),
        migrations.AlterField(
            model_name='activitymark_lettergrade',
            name='created_by',
            field=models.CharField(help_text='Userid who gives the mark', max_length=8),
        ),
        migrations.AlterField(
            model_name='activitymark_lettergrade',
            name='mark',
            field=models.CharField(choices=[('A+', 'A+ (Excellent performance)'), ('A', 'A (Excellent performance)'), ('A-', 'A- (Excellent performance)'), ('B+', 'B+ (Good performance)'), ('B', 'B (Good performance)'), ('B-', 'B- (Good performance)'), ('C+', 'C+ (Satisfactory performance)'), ('C', 'C (Satisfactory performance)'), ('C-', 'C- (Marginal performance)'), ('D', 'D (Marginal performance)'), ('F', 'F (Fail. Unsatisfactory Performance)'), ('N', 'N (Did not write exam or did not complete course)'), ('P', 'P (Satisfactory performance or better (pass, ungraded))'), ('DE', 'DE (Deferred grade)'), ('GN', 'GN (Grade not reported)'), ('IP', 'IP (In progress)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='groupactivitymark',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='groupactivitymark',
            name='numeric_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.NumericActivity'),
        ),
        migrations.AlterField(
            model_name='groupactivitymark_lettergrade',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='groupactivitymark_lettergrade',
            name='letter_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.LetterActivity'),
        ),
        migrations.AlterField(
            model_name='groupactivitymark_lettergrade',
            name='letter_grade',
            field=models.CharField(choices=[('A+', 'A+ (Excellent performance)'), ('A', 'A (Excellent performance)'), ('A-', 'A- (Excellent performance)'), ('B+', 'B+ (Good performance)'), ('B', 'B (Good performance)'), ('B-', 'B- (Good performance)'), ('C+', 'C+ (Satisfactory performance)'), ('C', 'C (Satisfactory performance)'), ('C-', 'C- (Marginal performance)'), ('D', 'D (Marginal performance)'), ('F', 'F (Fail. Unsatisfactory Performance)'), ('N', 'N (Did not write exam or did not complete course)'), ('P', 'P (Satisfactory performance or better (pass, ungraded))'), ('DE', 'DE (Deferred grade)'), ('GN', 'GN (Grade not reported)'), ('IP', 'IP (In progress)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='numeric_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.NumericGrade'),
        ),
        migrations.AlterField(
            model_name='studentactivitymark_lettergrade',
            name='letter_grade',
            field=models.ForeignKey(choices=[('A+', 'A+ (Excellent performance)'), ('A', 'A (Excellent performance)'), ('A-', 'A- (Excellent performance)'), ('B+', 'B+ (Good performance)'), ('B', 'B (Good performance)'), ('B-', 'B- (Good performance)'), ('C+', 'C+ (Satisfactory performance)'), ('C', 'C (Satisfactory performance)'), ('C-', 'C- (Marginal performance)'), ('D', 'D (Marginal performance)'), ('F', 'F (Fail. Unsatisfactory Performance)'), ('N', 'N (Did not write exam or did not complete course)'), ('P', 'P (Satisfactory performance or better (pass, ungraded))'), ('DE', 'DE (Deferred grade)'), ('GN', 'GN (Grade not reported)'), ('IP', 'IP (In progress)')], on_delete=django.db.models.deletion.PROTECT, to='grades.LetterGrade'),
        ),
    ]
