# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import marking.models


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0008_add_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitymark',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=marking.models.attachment_upload_to),
        ),
    ]
