# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 10:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0014_auto_20160623_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(db_index=True, help_text=b'Subject code, like "CMPT" or "FAN".', max_length=8),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='subject',
            field=models.CharField(db_index=True, help_text=b'Subject code, like "CMPT" or "FAN"', max_length=8),
        ),
    ]
