# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import bitfield.models
import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0019_switch_to_utf8mb4_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedoffering',
            name='campus',
            field=models.CharField(choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver')], max_length=5),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('TUT', 'Tutorial'), ('SEM', 'Seminar'), ('SEC', 'Section'), ('PRA', 'Practicum'), ('IND', 'Individual Work'), ('INS', 'INS'), ('WKS', 'Workshop'), ('FLD', 'Field School'), ('STD', 'Studio'), ('OLC', 'OLC'), ('RQL', 'RQL'), ('RSC', 'RSC'), ('STL', 'STL'), ('CNV', 'CNV'), ('OPL', 'Open Lab'), ('EXM', 'Exam'), ('CAN', 'Cancelled')], max_length=3),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='instr_mode',
            field=models.CharField(choices=[('CO', 'Co-Op'), ('DE', 'Distance Education'), ('GI', 'Graduate Internship'), ('P', 'In Person'), ('PO', 'In Person - Off Campus'), ('PR', 'Practicum')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='owner',
            field=models.ForeignKey(help_text='Unit that controls this offering', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(db_index=True, help_text='Course number, like "120" or "XX1".', max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(db_index=True, help_text='Subject code, like "CMPT" or "FAN".', max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='The course title.', max_length=30),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='campus',
            field=models.CharField(choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('TUT', 'Tutorial'), ('SEM', 'Seminar'), ('SEC', 'Section'), ('PRA', 'Practicum'), ('IND', 'Individual Work'), ('INS', 'INS'), ('WKS', 'Workshop'), ('FLD', 'Field School'), ('STD', 'Studio'), ('OLC', 'OLC'), ('RQL', 'RQL'), ('RSC', 'RSC'), ('STL', 'STL'), ('CNV', 'CNV'), ('OPL', 'Open Lab'), ('EXM', 'Exam'), ('CAN', 'Cancelled')], db_index=True, help_text='Component of the offering, like "LEC" or "LAB"', max_length=3),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Course'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='flags',
            field=bitfield.models.BitField(['write', 'quant', 'bhum', 'bsci', 'bsoc', 'combined'], default=0),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='instr_mode',
            field=models.CharField(choices=[('CO', 'Co-Op'), ('DE', 'Distance Education'), ('GI', 'Graduate Internship'), ('P', 'In Person'), ('PO', 'In Person - Off Campus'), ('PR', 'Practicum')], db_index=True, default='P', help_text='The instructional mode of the offering', max_length=2),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='number',
            field=models.CharField(db_index=True, help_text='Course number, like "120" or "XX1"', max_length=4),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='owner',
            field=models.ForeignKey(help_text='Unit that controls this offering', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='section',
            field=models.CharField(db_index=True, help_text='Section should be in the form "C100" or "D100"', max_length=4),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='subject',
            field=models.CharField(db_index=True, help_text='Subject code, like "CMPT" or "FAN"', max_length=8),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='title',
            field=models.CharField(db_index=True, help_text='The course title', max_length=30),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='units',
            field=models.PositiveSmallIntegerField(help_text='The number of credits received by (most?) students in the course', null=True),
        ),
        migrations.AlterField(
            model_name='enrolmenthistory',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='futureperson',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(help_text='Description of holiday, e.g. "Canada Day"', max_length=30),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('FULL', 'Classes cancelled, offices closed'), ('CLAS', 'Classes cancelled, offices open'), ('OPEN', 'Classes as scheduled')], help_text='Type of holiday: how does it affect schedules?', max_length=4),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='end_day',
            field=models.DateField(help_text='Ending day of the meeting'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='end_time',
            field=models.TimeField(help_text='End time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='labtut_section',
            field=models.CharField(blank=True, help_text='Section should be in the form "C101" or "D103".  None/blank for the non lab/tutorial events.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='meeting_type',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('MIDT', 'Midterm Exam'), ('EXAM', 'Exam'), ('LAB', 'Lab/Tutorial')], default='LEC', max_length=4),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_time', to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='room',
            field=models.CharField(help_text='Room (or other location) for the meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='start_day',
            field=models.DateField(help_text='Starting day of the meeting'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='start_time',
            field=models.TimeField(help_text='Start time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week of the meeting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='added_reason',
            field=models.CharField(choices=[('AUTO', 'Automatically added'), ('TRU', 'TRU/OU Distance Student'), ('CTA', 'CourSys-Appointed TA'), ('TAC', 'CourSys-Appointed TA'), ('TA', 'Additional TA'), ('TAIN', 'TA added by instructor'), ('INST', 'Additional Instructor'), ('UNK', 'Unknown/Other Reason')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='career',
            field=models.CharField(choices=[('UGRD', 'Undergraduate'), ('GRAD', 'Graduate'), ('NONS', 'Non-Student')], max_length=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='member',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of credits this course is worth.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='labtut_section',
            field=models.CharField(blank=True, help_text='Section should be in the form "C101" or "D103".', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='member',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('STUD', 'Student'), ('TA', 'TA'), ('INST', 'Instructor'), ('APPR', 'Grade Approver'), ('DROP', 'Dropped')], max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='person',
            name='emplid',
            field=models.PositiveIntegerField(db_index=True, help_text='Employee ID (i.e. student number)', unique=True, verbose_name='ID #'),
        ),
        migrations.AlterField(
            model_name='person',
            name='userid',
            field=models.CharField(blank=True, db_index=True, help_text='SFU Unix userid (i.e. part of SFU email address before the "@").', max_length=8, null=True, unique=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADVS', 'Advisor'), ('FAC', 'Faculty Member'), ('SESS', 'Sessional Instructor'), ('COOP', 'Co-op Staff'), ('INST', 'Other Instructor'), ('SUPV', 'Additional Supervisor'), ('DISC', 'Discipline Case Administrator'), ('DICC', 'Discipline Case Filer (email CC)'), ('ADMN', 'Departmental Administrator'), ('TAAD', 'TA Administrator'), ('TADM', 'Teaching Administrator'), ('GRAD', 'Grad Student Administrator'), ('GRPD', 'Graduate Program Director'), ('FUND', 'Grad Funding Administrator'), ('FDCC', 'Grad Funding Reminder CC'), ('TECH', 'Tech Staff'), ('GPA', 'GPA conversion system admin'), ('OUTR', 'Outreach Administrator'), ('INV', 'Inventory Administrator'), ('FACR', 'Faculty Viewer'), ('REPV', 'Report Viewer'), ('FACA', 'Faculty Administrator'), ('RELA', 'Relationship Database User'), ('SPAC', 'Space Administrator'), ('SYSA', 'System Administrator'), ('NONE', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='role',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='roleaccount',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='roleaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('ADVS', 'Advisor'), ('FAC', 'Faculty Member'), ('SESS', 'Sessional Instructor'), ('COOP', 'Co-op Staff'), ('INST', 'Other Instructor'), ('SUPV', 'Additional Supervisor'), ('DISC', 'Discipline Case Administrator'), ('DICC', 'Discipline Case Filer (email CC)'), ('ADMN', 'Departmental Administrator'), ('TAAD', 'TA Administrator'), ('TADM', 'Teaching Administrator'), ('GRAD', 'Grad Student Administrator'), ('GRPD', 'Graduate Program Director'), ('FUND', 'Grad Funding Administrator'), ('FDCC', 'Grad Funding Reminder CC'), ('TECH', 'Tech Staff'), ('GPA', 'GPA conversion system admin'), ('OUTR', 'Outreach Administrator'), ('INV', 'Inventory Administrator'), ('FACR', 'Faculty Viewer'), ('REPV', 'Report Viewer'), ('FACA', 'Faculty Administrator'), ('RELA', 'Relationship Database User'), ('SPAC', 'Space Administrator'), ('SYSA', 'System Administrator'), ('NONE', 'none')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='roleaccount',
            name='userid',
            field=models.CharField(db_index=True, help_text='SFU Unix userid (i.e. part of SFU email address before the "@").', max_length=8, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end',
            field=models.DateField(help_text='Last day of classes.'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(db_index=True, help_text='Semester name should be in the form "1097".', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start',
            field=models.DateField(help_text='First day of classes.'),
        ),
        migrations.AlterField(
            model_name='semesterweek',
            name='monday',
            field=models.DateField(help_text='Monday of this week.'),
        ),
        migrations.AlterField(
            model_name='semesterweek',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='semesterweek',
            name='week',
            field=models.PositiveSmallIntegerField(help_text='Week of the semester (typically 1-13)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='acad_org',
            field=models.CharField(blank=True, db_index=True, help_text='ACAD_ORG field from SIMS', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(db_index=True, help_text="The unit code, e.g. 'CMPT'.", max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text="The full name of the unit, e.g. 'School of Computing Science'.", max_length=60),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Next unit up in the hierarchy.', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
    ]
