# Generated by Django 2.2.11 on 2020-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0022_add_new_visit_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedoffering',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('TUT', 'Tutorial'), ('SEM', 'Seminar'), ('SEC', 'Section'), ('PRA', 'Practicum'), ('IND', 'Individual Work'), ('INS', 'INS'), ('WKS', 'Workshop'), ('FLD', 'Field School'), ('STD', 'Studio'), ('OLC', 'OLC'), ('RQL', 'RQL'), ('RSC', 'RSC'), ('STL', 'STL'), ('CNV', 'CNV'), ('OPL', 'Open Lab'), ('EXM', 'Exam'), ('CAP', 'Capstone Required'), ('INT', 'Internship Required'), ('CAP', 'Capstone'), ('COP', 'Work Integrated Learning'), ('THE', 'Thesis Research'), ('CAN', 'Cancelled')], max_length=3),
        ),
        migrations.AlterField(
            model_name='combinedoffering',
            name='instr_mode',
            field=models.CharField(choices=[('CO', 'Co-Op'), ('DE', 'Distance Education'), ('GI', 'Graduate Internship'), ('P', 'In Person'), ('PO', 'In Person - Off Campus'), ('PR', 'Practicum'), ('PF', 'In Person Field School')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('TUT', 'Tutorial'), ('SEM', 'Seminar'), ('SEC', 'Section'), ('PRA', 'Practicum'), ('IND', 'Individual Work'), ('INS', 'INS'), ('WKS', 'Workshop'), ('FLD', 'Field School'), ('STD', 'Studio'), ('OLC', 'OLC'), ('RQL', 'RQL'), ('RSC', 'RSC'), ('STL', 'STL'), ('CNV', 'CNV'), ('OPL', 'Open Lab'), ('EXM', 'Exam'), ('CAP', 'Capstone Required'), ('INT', 'Internship Required'), ('CAP', 'Capstone'), ('COP', 'Work Integrated Learning'), ('THE', 'Thesis Research'), ('CAN', 'Cancelled')], db_index=True, help_text='Component of the offering, like "LEC" or "LAB"', max_length=3),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='instr_mode',
            field=models.CharField(choices=[('CO', 'Co-Op'), ('DE', 'Distance Education'), ('GI', 'Graduate Internship'), ('P', 'In Person'), ('PO', 'In Person - Off Campus'), ('PR', 'Practicum'), ('PF', 'In Person Field School')], db_index=True, default='P', help_text='The instructional mode of the offering', max_length=2),
        ),
    ]
