# Generated by Django 3.2.25 on 2025-08-27 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0026_add_to_enrolment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='userid',
            field=models.CharField(blank=True, db_index=True, help_text='SFU Unix userid (i.e. part of SFU email address before the "@").', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='userids can contain only letters and numbers', regex='^[a-z0-9\\-_]{2,12}$')], verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADVS', 'Advisor'), ('ADVM', 'Advisor Manager'), ('FAC', 'Faculty Member'), ('SESS', 'Sessional Instructor'), ('COOP', 'Co-op Staff'), ('INST', 'Other Instructor'), ('SUPV', 'Additional Supervisor'), ('DISC', 'Discipline Case Administrator'), ('DICC', 'Discipline Case Filer (email CC)'), ('ADMN', 'Departmental Administrator'), ('TAAD', 'TA Administrator'), ('TADM', 'Teaching Administrator'), ('GRAD', 'Grad Student Administrator'), ('GRPD', 'Graduate Program Director'), ('FUND', 'Grad Funding Administrator'), ('FDMA', 'Grad Funding Manager'), ('FDRE', 'Grad Funding Requester'), ('FDCC', 'Grad Funding Reminder CC'), ('TECH', 'Tech Staff'), ('GPA', 'GPA conversion system admin'), ('OUTR', 'Outreach Administrator'), ('INV', 'Inventory Administrator'), ('FACR', 'Faculty Viewer'), ('REPV', 'Report Viewer'), ('FACA', 'Faculty Administrator'), ('RELA', 'Relationship Database User'), ('SPAC', 'Space Administrator'), ('FORM', 'Form Administrator'), ('SYSA', 'System Administrator'), ('NONE', 'none')], max_length=4),
        ),
        migrations.AlterField(
            model_name='roleaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('ADVS', 'Advisor'), ('ADVM', 'Advisor Manager'), ('FAC', 'Faculty Member'), ('SESS', 'Sessional Instructor'), ('COOP', 'Co-op Staff'), ('INST', 'Other Instructor'), ('SUPV', 'Additional Supervisor'), ('DISC', 'Discipline Case Administrator'), ('DICC', 'Discipline Case Filer (email CC)'), ('ADMN', 'Departmental Administrator'), ('TAAD', 'TA Administrator'), ('TADM', 'Teaching Administrator'), ('GRAD', 'Grad Student Administrator'), ('GRPD', 'Graduate Program Director'), ('FUND', 'Grad Funding Administrator'), ('FDMA', 'Grad Funding Manager'), ('FDRE', 'Grad Funding Requester'), ('FDCC', 'Grad Funding Reminder CC'), ('TECH', 'Tech Staff'), ('GPA', 'GPA conversion system admin'), ('OUTR', 'Outreach Administrator'), ('INV', 'Inventory Administrator'), ('FACR', 'Faculty Viewer'), ('REPV', 'Report Viewer'), ('FACA', 'Faculty Administrator'), ('RELA', 'Relationship Database User'), ('SPAC', 'Space Administrator'), ('FORM', 'Form Administrator'), ('SYSA', 'System Administrator'), ('NONE', 'none')], max_length=4, null=True),
        ),
    ]
