# Generated by Django 2.2.1 on 2019-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_events_from_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='eol_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Life Date'),
        ),
        migrations.AddField(
            model_name='asset',
            name='express_service_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='service_records',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('SWAG', 'Swag'), ('RESR', 'Research'), ('GEN', 'General'), ('BROC', 'Brochures'), ('DISP', 'Display'), ('SURP', 'Surplus'), ('BANN', 'Banners'), ('EVEN', 'Events'), ('TECH', 'Tech Support'), ('OFF', 'Office Supplies'), ('TEAC', 'Teaching'), ('ADMN', 'Admin Support')], default='GEN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, help_text='Service Tag, or SFU Asset Tag number, if it exists', max_length=60, null=True, verbose_name='Service Tag'),
        ),
        migrations.AlterField(
            model_name='assetchangerecord',
            name='qty',
            field=models.IntegerField(help_text="The change in quantity.  For removal of item, make it a negative number. For adding items, make it a positive.  e.g. '-2' if someone removed two of this item for something", verbose_name='Quantity adjustment'),
        ),
    ]
