# Generated by Django 2.2.4 on 2019-08-14 15:04

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_fields_to_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='date_shipped',
            field=models.DateField(blank=True, null=True, verbose_name='Date Shipped/Delivered'),
        ),
        migrations.AddField(
            model_name='asset',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='Currently In Use'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If this item is assigned to a particular user,please add them here.', null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Calibration/Service Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('RESR', 'Research'), ('BROC', 'Brochures'), ('TECH', 'Tech Support'), ('OFF', 'Office Supplies'), ('TEAC', 'Teaching'), ('GEN', 'General'), ('ADMN', 'Admin Support'), ('EVEN', 'Events'), ('ELEC', 'Electronics'), ('SWAG', 'Swag')], default='GEN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='assetdocumentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=inventory.models.asset_attachment_upload_to),
        ),
    ]
