# Generated by Django 2.2.11 on 2020-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_stock_status_to_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetchangerecord',
            name='event',
            field=models.CharField(blank=True, help_text='If this change is associated with an event, fill in the event name here.', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('OFF', 'Office Supplies'), ('ELEC', 'Electronics'), ('BROC', 'Brochures'), ('GEN', 'General'), ('RESR', 'Research'), ('TEAC', 'Teaching'), ('SWAG', 'Swag'), ('EVEN', 'Events'), ('TECH', 'Tech Support'), ('ADMN', 'Admin Support')], default='GEN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stock_status',
            field=models.DecimalField(blank=True, choices=[(3, 'Unknown'), (2, 'In Stock'), (0, 'Out of stock'), (1, 'Low Stock')], decimal_places=0, max_digits=1, null=True),
        ),
    ]
