# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_event_to_change_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('PPE', 'PPE'), ('EVEN', 'Events'), ('SWAG', 'Swag'), ('OFF', 'Office Supplies'), ('TEAC', 'Teaching'), ('ADMN', 'Admin Support'), ('RESR', 'Research'), ('TECH', 'Tech Support'), ('BROC', 'Brochures')], default='GEN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stock_status',
            field=models.DecimalField(blank=True, choices=[(1, 'Low Stock'), (2, 'In Stock'), (0, 'Out of stock'), (3, 'Unknown')], decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='assetdocumentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=inventory.models.asset_attachment_upload_to),
        ),
    ]
