# Generated by Django 5.2.17 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GEN", "General"),
                    ("PPE", "PPE"),
                    ("BROC", "Brochures"),
                    ("EVEN", "Events"),
                    ("RESR", "Research"),
                    ("ADMN", "Admin Support"),
                    ("TECH", "Tech Support"),
                    ("SWAG", "Swag"),
                    ("TEAC", "Teaching"),
                    ("OFF", "Office Supplies"),
                ],
                default="GEN",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="stock_status",
            field=models.DecimalField(
                blank=True,
                choices=[
                    (3, "Unknown"),
                    (2, "In Stock"),
                    (0, "Out of stock"),
                    (1, "Low Stock"),
                ],
                decimal_places=0,
                max_digits=1,
                null=True,
            ),
        ),
    ]
