# Generated by Django 2.2.4 on 2020-03-26 11:03

from django.db import migrations
from onlineforms.fieldtypes.other import new_file_secret


def fill_secrets(apps, schema_editor):
    # fill in the file secret, since it's new
    FieldSubmission = apps.get_model('onlineforms', 'FieldSubmission')
    for fieldsub in FieldSubmission.objects.filter(field__fieldtype='FILE'):
        if 'secret' not in fieldsub.data or not fieldsub.data['secret']:
            fieldsub.data['secret'] = new_file_secret()
            fieldsub.save()


def remove_secrets(apps, schema_editor):
    FieldSubmission = apps.get_model('onlineforms', 'FieldSubmission')
    for fieldsub in FieldSubmission.objects.filter(field__fieldtype='FILE'):
        if 'secret' in fieldsub.data:
            del fieldsub.data['secret']
            fieldsub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforms', '0005_on_delete'),
    ]

    operations = [
        migrations.RunPython(fill_secrets, reverse_code=remove_secrets),
    ]
