# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20160816_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrule',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='notify',
            field=models.BooleanField(default=False, help_text='Email this person when a report completes.'),
        ),
        migrations.AlterField(
            model_name='accessrule',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='hardcodedreport',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='hardcodedreport',
            name='file_location',
            field=models.CharField(choices=[('bad_first_semester.py', 'bad_first_semester.py'), ('bad_gpas.py', 'bad_gpas.py'), ('cmpt165_after_cmpt.py', 'cmpt165_after_cmpt.py'), ('cmpt_125_after_placement_test.py', 'cmpt_125_after_placement_test.py'), ('cmpt_course_history.py', 'cmpt_course_history.py'), ('cmpt_grad_coops.py', 'cmpt_grad_coops.py'), ('cmpt_minors_upper_division.py', 'cmpt_minors_upper_division.py'), ('cmpt_program_gpas.py', 'cmpt_program_gpas.py'), ('diversity_in_cmpt_120.py', 'diversity_in_cmpt_120.py'), ('ensc_150_and_250_but_not_215.py', 'ensc_150_and_250_but_not_215.py'), ('ensc_course_history.py', 'ensc_course_history.py'), ('enscpro_coop.py', 'enscpro_coop.py'), ('fake_report.py', 'fake_report.py'), ('fas_courses_by_instructor.py', 'fas_courses_by_instructor.py'), ('fas_international.py', 'fas_international.py'), ('fas_with_email.py', 'fas_with_email.py'), ('five_retakes.py', 'five_retakes.py'), ('gender_diversity_accept_vs_enroll.py', 'gender_diversity_accept_vs_enroll.py'), ('immediate_retake_report.py', 'immediate_retake_report.py'), ('low_gpa_or_no_coop.py', 'low_gpa_or_no_coop.py'), ('majors_in_courses.py', 'majors_in_courses.py'), ('mse_410_less_than_3_coops.py', 'mse_410_less_than_3_coops.py'), ('mse_course_history.py', 'mse_course_history.py')], help_text='The location of this report, on disk.', max_length=80),
        ),
        migrations.AlterField(
            model_name='query',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the report.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(help_text='Name of the report.', max_length=150),
        ),
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='result',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='table',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='run',
            name='manual',
            field=models.BooleanField(default=False, help_text='Was this run requested manually (as opposed to scheduled)?'),
        ),
        migrations.AlterField(
            model_name='run',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='schedule_type',
            field=models.CharField(choices=[('ONE', 'One-Time'), ('DAI', 'Daily'), ('MON', 'Monthly'), ('YEA', 'Yearly')], default='ONE', max_length=3),
        ),
    ]
