# Generated by Django 3.2.14 on 2025-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerule',
            name='next_run',
            field=models.DateTimeField(null=True),
        ),
    ]
