# Generated by Django 5.2.17 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardcodedreport",
            name="file_location",
            field=models.CharField(
                choices=[
                    ("bad_first_semester.py", "bad_first_semester.py"),
                    ("bad_gpas.py", "bad_gpas.py"),
                    ("cmpt165_after_cmpt.py", "cmpt165_after_cmpt.py"),
                    (
                        "cmpt_125_after_placement_test.py",
                        "cmpt_125_after_placement_test.py",
                    ),
                    ("cmpt_course_history.py", "cmpt_course_history.py"),
                    ("cmpt_grad_coops.py", "cmpt_grad_coops.py"),
                    ("cmpt_grad_requirements.py", "cmpt_grad_requirements.py"),
                    ("cmpt_minors_upper_division.py", "cmpt_minors_upper_division.py"),
                    ("cmpt_program_gpas.py", "cmpt_program_gpas.py"),
                    ("cmpt_tas_conflict_roles.py", "cmpt_tas_conflict_roles.py"),
                    ("cmpt_tas_courses.py", "cmpt_tas_courses.py"),
                    ("cmpt_waiting_list.py", "cmpt_waiting_list.py"),
                    ("cs_gender_exploration.py", "cs_gender_exploration.py"),
                    ("cs_gender_table.py", "cs_gender_table.py"),
                    ("discipline_cases.py", "discipline_cases.py"),
                    ("diversity_in_cmpt_120.py", "diversity_in_cmpt_120.py"),
                    (
                        "ensc_150_and_250_but_not_215.py",
                        "ensc_150_and_250_but_not_215.py",
                    ),
                    ("ensc_course_history.py", "ensc_course_history.py"),
                    ("enscpro_coop.py", "enscpro_coop.py"),
                    ("fake_report.py", "fake_report.py"),
                    (
                        "fas_advisor_visit_surveys_monthly.py",
                        "fas_advisor_visit_surveys_monthly.py",
                    ),
                    (
                        "fas_advisor_visits_annually.py",
                        "fas_advisor_visits_annually.py",
                    ),
                    (
                        "fas_advisor_visits_semesterly.py",
                        "fas_advisor_visits_semesterly.py",
                    ),
                    ("fas_advisor_visits_weekly.py", "fas_advisor_visits_weekly.py"),
                    (
                        "fas_browse_course_offerings.py",
                        "fas_browse_course_offerings.py",
                    ),
                    ("fas_courses_by_instructor.py", "fas_courses_by_instructor.py"),
                    ("fas_crosslisted_courses.py", "fas_crosslisted_courses.py"),
                    ("fas_grad_status_counts.py", "fas_grad_status_counts.py"),
                    ("fas_international.py", "fas_international.py"),
                    ("fas_offerings.py", "fas_offerings.py"),
                    ("fas_supervisors.py", "fas_supervisors.py"),
                    ("fas_ta_grads.py", "fas_ta_grads.py"),
                    ("fas_tas_courses.py", "fas_tas_courses.py"),
                    ("fas_teaching_by_instructor.py", "fas_teaching_by_instructor.py"),
                    ("fas_with_email.py", "fas_with_email.py"),
                    ("five_retakes.py", "five_retakes.py"),
                    (
                        "gender_diversity_accept_vs_enroll.py",
                        "gender_diversity_accept_vs_enroll.py",
                    ),
                    ("immediate_retake_report.py", "immediate_retake_report.py"),
                    ("low_gpa_or_no_coop.py", "low_gpa_or_no_coop.py"),
                    ("majors_in_courses.py", "majors_in_courses.py"),
                    ("mse_410_less_than_3_coops.py", "mse_410_less_than_3_coops.py"),
                    ("mse_course_history.py", "mse_course_history.py"),
                ],
                help_text="The location of this report, on disk.",
                max_length=80,
            ),
        ),
    ]
