# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ta.models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0006_add_training_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspreference',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAApplication'),
        ),
        migrations.AlterField(
            model_name='campuspreference',
            name='campus',
            field=models.CharField(choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver')], max_length=5),
        ),
        migrations.AlterField(
            model_name='campuspreference',
            name='pref',
            field=models.CharField(choices=[('PRF', 'Preferred'), ('WIL', 'Willing'), ('NOT', 'Not willing')], max_length=3),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description',
            field=models.CharField(help_text="Description of the work for a course, as it will appear on the contract. (e.g. 'Office/marking')", max_length=60),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='labtut',
            field=models.BooleanField(default=False, help_text='Does this description get the 0.17 BU bonus?', verbose_name='Lab/Tutorial?'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAApplication'),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Course'),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='exper',
            field=models.CharField(choices=[('FAM', 'Very familiar with course material'), ('SOM', 'Somewhat familiar with course material'), ('NOT', 'Not familiar with course material')], max_length=3, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='taken',
            field=models.CharField(choices=[('YES', 'Yes: this course at SFU'), ('SIM', 'Yes: a similar course elsewhere'), ('KNO', 'No, but I know the course material'), ('NO', "No, I don't know the material well")], max_length=3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAPosting'),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAApplication'),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.CharField(choices=[('EXPR', 'Expert'), ('GOOD', 'Good'), ('SOME', 'Some'), ('NONE', 'None')], max_length=4),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.Skill'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='base_units',
            field=models.DecimalField(decimal_places=2, default=5, help_text="Maximum number of base units (BU's) you would accept. Each BU represents a maximum of 42 hours of work for the semester. TA appointments can consist of 2 to 5 base units and are based on course enrollments and department requirements.", max_digits=4),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='category',
            field=models.CharField(choices=[('GTA1', 'Masters'), ('GTA2', 'PhD'), ('UTA', 'Undergrad'), ('ETA', 'External')], max_length=4, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional comments'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='course_load',
            field=models.TextField(blank=True, help_text='Describe the intended course load of the semester being applied for.', verbose_name='Intended course load'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='current_program',
            field=models.CharField(blank=True, help_text='In what department are you a student (e.g. "CMPT", "ENSC", if applicable)?', max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe any other experience that you think may be relevant to these courses.', null=True, verbose_name='Additional Experience'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='new_workers_training',
            field=models.BooleanField(default=False, help_text='WorkSafe BC requires all new employees to take a safety orientation.  SFU has a short online module you can take here <https://canvas.sfu.ca/enroll/RR8WDW> and periodically offers classroom sessions of the same material.  Some research and instructional laboratories may require additional training, contact the faculty member in charge of your lab(s) for details.', verbose_name='I have completed the mandatory SFU Safety Orientation training'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='other_support',
            field=models.TextField(blank=True, help_text='Do you have a merit based scholarship or fellowship (e.g. FAS Graduate Fellowship) in the semester that you are applying for? ', null=True, verbose_name='Other financial support'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAPosting'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Please attach your Curriculum Vitae (CV).', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=ta.models._file_upload_to, verbose_name='Curriculum Vitae (CV)'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='sin',
            field=models.CharField(blank=True, help_text='Social insurance number (required for receiving payments)', max_length=30, verbose_name='SIN'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='transcript',
            field=models.FileField(blank=True, help_text='Please attach your unofficial transcript.', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=ta.models._file_upload_to),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAApplication'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='appt',
            field=models.CharField(choices=[('INIT', 'Initial appointment to this position'), ('REAP', 'Reappointment to same position or revision to appointment')], default='INIT', max_length=4, verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='appt_category',
            field=models.CharField(choices=[('GTA1', 'Masters'), ('GTA2', 'PhD'), ('UTA', 'Undergrad'), ('ETA', 'External')], default='GTA1', max_length=4, verbose_name='Appointment Category'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='appt_cond',
            field=models.BooleanField(default=False, verbose_name='Conditional'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='appt_tssu',
            field=models.BooleanField(default=True, verbose_name='Appointment in TSSU'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='deadline',
            field=models.DateField(help_text='Deadline for the applicant to accept/decline the offer', verbose_name='Acceptance Deadline'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='pay_per_bu',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pay per Base Unit Semester Rate.'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='position_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ra.Account'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAPosting'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='scholarship_per_bu',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Scholarship per Base Unit Semester Rate.'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='sin',
            field=models.CharField(help_text='Social insurance number', max_length=30, verbose_name='SIN'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='status',
            field=models.CharField(choices=[('NEW', 'Draft'), ('OPN', 'Offered'), ('REJ', 'Rejected'), ('ACC', 'Accepted'), ('SGN', 'Contract Signed'), ('CAN', 'Cancelled')], default='NEW', max_length=3, verbose_name='Appointment Status'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.TAContract'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.CourseOffering'),
        ),
        migrations.AlterField(
            model_name='tacourse',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ta.CourseDescription'),
        ),
        migrations.AlterField(
            model_name='taposting',
            name='closes',
            field=models.DateField(help_text='Closing date for the posting'),
        ),
        migrations.AlterField(
            model_name='taposting',
            name='opens',
            field=models.DateField(help_text='Opening date for the posting'),
        ),
        migrations.AlterField(
            model_name='taposting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='taposting',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='taposting',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='tug',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tug',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member'),
        ),
    ]
