# Generated by Django 2.0.1 on 2018-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0008_course_pref_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreference',
            name='exper',
            field=models.CharField(blank=True, choices=[('FAM', 'Very familiar with course material'), ('SOM', 'Somewhat familiar with course material'), ('NOT', 'Not familiar with course material')], max_length=3, null=True, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='coursepreference',
            name='taken',
            field=models.CharField(blank=True, choices=[('YES', 'Yes: this course at SFU'), ('SIM', 'Yes: a similar course elsewhere'), ('KNO', 'No, but I know the course material'), ('NO', "No, I don't know the material well")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='current_program',
            field=models.CharField(blank=True, choices=[('CMPT', 'CMPT student'), ('OTHR', 'Other program'), ('NONS', 'Not a student')], help_text='In what department are you a student?', max_length=100, null=True, verbose_name='Department'),
        ),
    ]
