# Generated by Django 2.0.3 on 2018-03-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0020_on_delete'),
        ('ta', '0009_ta_simplify'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAContractEmailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='e.g. "Please find enclosed your TA Contract..."')),
                ('unit', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='contract_email_text', to='coredata.Unit')),
            ],
        ),
    ]
