# Generated by Django 2.2.15 on 2021-06-22 15:09

import django.core.files.storage
from django.db import migrations, models
import ta.models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0010_add_contract_accept_contract_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='taapplication',
            name='validsin',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', help_text='Do you have valid SIN at the time of employment?', max_length=3, verbose_name='SIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campuspreference',
            name='pref',
            field=models.CharField(choices=[('PRF', 'Preferred'), ('NOP', 'No Preference')], max_length=3),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='preference_comment',
            field=models.TextField(blank=True, help_text='If you are applying for a course with multiple sections, please indicate which section you prefer.', null=True, verbose_name='Course preference comment'),
        ),
    ]
