# Generated by Django 3.2.15 on 2022-10-17 12:03

import django.core.files.storage
from django.db import migrations, models
import ta.models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0011_change_sin_campuspref'),
    ]

    operations = [
        migrations.AddField(
            model_name='taapplication',
            name='program_comment',
            field=models.CharField(blank=True, help_text='If you select "Other program" in Department, please indicate which programs did you study.', max_length=100, null=True, verbose_name='Other program comment'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Please attach your Curriculum Vitae (CV).', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=ta.models._file_upload_to, verbose_name='Curriculum Vitae (CV)'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='transcript',
            field=models.FileField(blank=True, help_text='Please attach your unofficial transcript.', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=ta.models._file_upload_to),
        ),
    ]
