# Generated by Django 3.2.25 on 2024-04-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [        
        ('ta', '0014_tacontract_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAWorkloadReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_now=True)),
                ('reviewhour', models.BooleanField(help_text='Choose "yes" if further review is required.')),
                ('reviewcomment', models.TextField(help_text='If No, explain briefly')),
                ('reviewsignature', models.CharField(help_text="Instruction's Signature", max_length=100)),
                ('reviewdate', models.DateField(help_text='Year/Month/Day')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coredata.member')),
            ],
        ),
    ]
