# Generated by Django 3.2.25 on 2024-07-02 14:43

import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0015_ta_workload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_appoint', models.BooleanField(blank=True, help_text="TA's First Appoint?", null=True)),
                ('draft', models.BooleanField(default=False)),
                ('criteria_lab_prep', models.IntegerField(blank=True, null=True, verbose_name='Preparation of Lab/Tutorial Material')),
                ('criteria_meet_deadline', models.IntegerField(blank=True, null=True, verbose_name='Meets Deadlines')),
                ('criteria_maintain_hour', models.IntegerField(blank=True, null=True, verbose_name='Maintains Office Hours')),
                ('criteria_attend_plan', models.IntegerField(blank=True, null=True, verbose_name='Attendance at Planning/Coordinating Meetings')),
                ('criteria_attend_lec', models.IntegerField(blank=True, null=True, verbose_name='Attendance at Lectures')),
                ('criteria_grading_fair', models.IntegerField(blank=True, null=True, verbose_name='Grading Fair/Consistent')),
                ('criteria_lab_performance', models.IntegerField(blank=True, null=True, verbose_name='Performance in Lab/Tutorial')),
                ('criteria_quality_of_feedback', models.IntegerField(blank=True, null=True, verbose_name='Quality of Feedback')),
                ('criteria_quiz_prep', models.IntegerField(blank=True, null=True, verbose_name='Quiz Preparation/Assist in Exam Preparation')),
                ('criteria_instr_content', models.IntegerField(blank=True, null=True, verbose_name='Instructional Content')),
                ('criteria_others', models.IntegerField(blank=True, null=True, verbose_name='Other Job Requirements')),
                ('criteria_other_comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('positive_comment', models.TextField(blank=True, null=True, verbose_name="Please comment on the TA's positive contributions to instruction (e.g. teaching methods, grading, ability to lead discussion) - or other noteworthy strengths")),
                ('improve_comment', models.TextField(blank=True, null=True, verbose_name="Please comment on those duties which you noted as not meeting job requirements and suggest ways in which the TA's performance could be improved")),
                ('overall_evalation', models.BooleanField(blank=True, null=True, verbose_name='Overall Meets Jobs Requirements')),
                ('recommend_TA', models.BooleanField(blank=True, null=True, verbose_name='Would you recommend this TA for reappointment?')),
                ('no_recommend_comment', models.TextField(blank=True, null=True, verbose_name='If No, explain briefly')),
                ('instructor_sign', models.CharField(max_length=200, verbose_name="Instruction's Signature")),
                ('instructor_signdate', models.DateField(help_text='Year-Month-Day', verbose_name='Evaluation Date')),
                ('ta_comment', models.TextField(blank=True, null=True, verbose_name="TA's comment")),
                ('ta_sign', models.CharField(blank=True, max_length=200, null=True, verbose_name="TA's Signature")),
                ('ta_signdate', models.DateField(blank=True, help_text='Year-Month-Day', null=True, verbose_name='TA Signed Date')),
                ('last_update', models.DateField(auto_now=True)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coredata.member')),
            ],
        ),
    ]
