# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import ta.models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0017_tug_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Please attach your Curriculum Vitae (CV).', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ta.models._file_upload_to, verbose_name='Curriculum Vitae (CV)'),
        ),
        migrations.AlterField(
            model_name='taapplication',
            name='transcript',
            field=models.FileField(blank=True, help_text='Please attach your unofficial transcript.', max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ta.models._file_upload_to),
        ),
    ]
