# Generated by Django 3.2.25 on 2025-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0018_trivial_migration_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='taapplication',
            name='physical_present_declare',
            field=models.BooleanField(default=False, help_text='All CS courses are to be primarily conducted in person. All Teaching Assistants (TAs) are required to be physically present for all assigned duties throughout the entirety of their appointment. Work distribution will adhere to the Time Use Guidelines, and TAs are obligated to diligently track and report their hours as per standard procedure.', verbose_name='I agree to be physically present on campus for all assigned duties throughout the entirety of my appointment'),
        ),
        migrations.AlterField(
            model_name='tacontract',
            name='remarks',
            field=models.TextField(blank=True, default='All CS courses are to be primarily conducted in person. All Teaching Assistants (TAs) are required to be physically present for all assigned duties throughout the entirety of their appointment. Work distribution will adhere to the Time Use Guidelines, and TAs are obligated to diligently track and report their hours as per standard procedure.'),
        ),
    ]
