# Generated by Django 5.2.17 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ta", "0018_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taapplication",
            name="new_workers_training",
            field=models.BooleanField(
                default=False,
                help_text='Have you completed the University\'s safety orientation? SFU has a <a href="https://sfu.instructure.com/enroll/YXTRE6">short online module</a> you can take onlineand periodically offers classroom sessions of the same material.  Some research and instructional laboratories may require additional training, contact the faculty member in charge of your lab(s) for details.',
                verbose_name="I have completed the SFU Safety Orientation training",
            ),
        ),
    ]
