# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0009_add_removed_field_to_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='label',
            field=models.CharField(max_length=150),
        ),
    ]
