# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import grad.models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0010_shorten_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedrequirement',
            name='date',
            field=models.DateField(blank=True, help_text='Date the requirement was completed (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='completedrequirement',
            name='notes',
            field=models.TextField(blank=True, help_text='Other notes', null=True),
        ),
        migrations.AlterField(
            model_name='completedrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradRequirement'),
        ),
        migrations.AlterField(
            model_name='completedrequirement',
            name='semester',
            field=models.ForeignKey(help_text='Semester when the requirement was completed', on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='completedrequirement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='completedrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
        migrations.AlterField(
            model_name='externaldocument',
            name='file_attachment',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=grad.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='externaldocument',
            name='name',
            field=models.CharField(help_text='A short description of what this file contains.', max_length=100),
        ),
        migrations.AlterField(
            model_name='externaldocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='financialcomment',
            name='comment_type',
            field=models.CharField(choices=[('SCO', 'Scholarship'), ('TA', 'TA'), ('RA', 'RA'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
        migrations.AlterField(
            model_name='financialcomment',
            name='created_by',
            field=models.CharField(help_text='Entered by (userid)', max_length=32),
        ),
        migrations.AlterField(
            model_name='financialcomment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='financialcomment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='gradflag',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='gradflagvalue',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradFlag'),
        ),
        migrations.AlterField(
            model_name='gradflagvalue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='gradprogram',
            name='created_by',
            field=models.CharField(help_text='Grad Program created by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='gradprogram',
            name='modified_by',
            field=models.CharField(help_text='Grad Program modified by.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gradprogram',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique_with=('unit',)),
        ),
        migrations.AlterField(
            model_name='gradprogram',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='gradprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
        migrations.AlterField(
            model_name='gradprogramhistory',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradProgram'),
        ),
        migrations.AlterField(
            model_name='gradprogramhistory',
            name='start_semester',
            field=models.ForeignKey(help_text='Semester when the student entered the program', on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='gradprogramhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='gradrequirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradProgram'),
        ),
        migrations.AlterField(
            model_name='gradrequirement',
            name='series',
            field=models.PositiveIntegerField(db_index=True, help_text='The category of requirement for searching by requirement, across programs'),
        ),
        migrations.AlterField(
            model_name='gradrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='end',
            field=models.ForeignKey(blank=True, help_text='Final semester of this status: blank for ongoing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_semester', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='notes',
            field=models.TextField(blank=True, help_text='Other notes'),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='start',
            field=models.ForeignKey(help_text='Semester when this status is effective', on_delete=django.db.models.deletion.PROTECT, related_name='start_semester', to='coredata.Semester', verbose_name='Effective Semester'),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date this status is effective (optional)', null=True, verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='status',
            field=models.CharField(choices=[('INCO', 'Incomplete Application'), ('COMP', 'Complete Application'), ('INRE', 'Application In-Review'), ('HOLD', 'Hold Application'), ('OFFO', 'Offer Out'), ('REJE', 'Rejected Application'), ('DECL', 'Declined Offer'), ('EXPI', 'Expired Application'), ('CONF', 'Confirmed Acceptance'), ('CANC', 'Cancelled Acceptance'), ('ARIV', 'Arrived'), ('ACTI', 'Active'), ('PART', 'Part-Time'), ('LEAV', 'On-Leave'), ('WIDR', 'Withdrawn'), ('GRAD', 'Graduated'), ('NOND', 'Non-degree'), ('GONE', 'Gone'), ('ARSP', 'Completed Special'), ('TRIN', 'Transferred from another department'), ('TROU', 'Transferred to another department'), ('DELE', 'Deleted Record'), ('DEFR', 'Deferred'), ('GAPL', 'Applied for Graduation'), ('GAPR', 'Graduation Approved')], max_length=4),
        ),
        migrations.AlterField(
            model_name='gradstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='campus',
            field=models.CharField(blank=True, choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver'), ('MULTI', 'Multiple Campuses')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional information.', max_length=250),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='created_by',
            field=models.CharField(help_text='Grad Student created by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='current_status',
            field=models.CharField(choices=[('INCO', 'Incomplete Application'), ('COMP', 'Complete Application'), ('INRE', 'Application In-Review'), ('HOLD', 'Hold Application'), ('OFFO', 'Offer Out'), ('REJE', 'Rejected Application'), ('DECL', 'Declined Offer'), ('EXPI', 'Expired Application'), ('CONF', 'Confirmed Acceptance'), ('CANC', 'Cancelled Acceptance'), ('ARIV', 'Arrived'), ('ACTI', 'Active'), ('PART', 'Part-Time'), ('LEAV', 'On-Leave'), ('WIDR', 'Withdrawn'), ('GRAD', 'Graduated'), ('NOND', 'Non-degree'), ('GONE', 'Gone'), ('ARSP', 'Completed Special'), ('TRIN', 'Transferred from another department'), ('TROU', 'Transferred to another department'), ('DELE', 'Deleted Record'), ('DEFR', 'Deferred'), ('GAPL', 'Applied for Graduation'), ('GAPR', 'Graduation Approved')], db_index=True, help_text='Current student status', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='end_semester',
            field=models.ForeignKey(help_text='Semester when the student finished/left the program.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grad_end_sem', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='english_fluency',
            field=models.CharField(blank=True, help_text='I.e. Read, Write, Speak, All.', max_length=50),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='modified_by',
            field=models.CharField(help_text='Grad Student modified by.', max_length=32, null=True, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='mother_tongue',
            field=models.CharField(blank=True, help_text='I.e. English, Chinese, French', max_length=25),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='passport_issued_by',
            field=models.CharField(blank=True, help_text='I.e. US, China', max_length=30),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='person',
            field=models.ForeignKey(help_text='Type in student ID or number.', on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradProgram'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='research_area',
            field=models.TextField(blank=True, verbose_name='Research Area'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='start_semester',
            field=models.ForeignKey(help_text='Semester when the student started the program.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grad_start_sem', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='closing',
            field=models.CharField(default='Sincerely', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='content',
            field=models.TextField(help_text="I.e. 'This is to confirm Mr. Baker ... '"),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.CharField(help_text='Letter generation requseted by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(help_text='The sending date of the letter'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='from_lines',
            field=models.TextField(help_text='Name (and title) of the signer, e.g. "John Smith, Program Director"'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='from_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.LetterTemplate'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to_lines',
            field=models.TextField(blank=True, help_text='Delivery address for the letter', null=True),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='content',
            field=models.TextField(help_text="I.e. 'This is to confirm {{title}} {{last_name}} ... '"),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='created_by',
            field=models.CharField(help_text='Letter template created by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='otherfunding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Funding Amount'),
        ),
        migrations.AlterField(
            model_name='otherfunding',
            name='eligible',
            field=models.BooleanField(default=True, help_text='Does this funding count towards promises of support?'),
        ),
        migrations.AlterField(
            model_name='otherfunding',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_funding', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='otherfunding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='result',
            field=models.CharField(choices=[('GOOD', 'Good'), ('SATI', 'Satisfactory'), ('CONC', 'Satisfactory with Concerns'), ('UNST', 'Unsatisfactory')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Promise Amount'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='end_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promise_end', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='start_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promise_start', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Scholarship Amount'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='end_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_end', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.ScholarshipType'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='start_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_start', to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='scholarshiptype',
            name='eligible',
            field=models.BooleanField(default=True, help_text='Does this scholarship count towards promises of support?'),
        ),
        migrations.AlterField(
            model_name='scholarshiptype',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='created_by',
            field=models.CharField(help_text='Committee member added by.', max_length=32),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='external',
            field=models.CharField(blank=True, help_text='Details if not an SFU internal member', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='modified_by',
            field=models.CharField(help_text='Committee member modified by.', max_length=32, null=True, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grad.GradStudent'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.Person', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_type',
            field=models.CharField(choices=[('SEN', 'Senior Supervisor'), ('COS', 'Co-senior Supervisor'), ('COM', 'Supervisor'), ('CHA', 'Defence Chair'), ('EXT', 'External Examiner'), ('SFU', 'SFU Examiner'), ('POT', 'Potential Supervisor')], max_length=3),
        ),
    ]
