# Generated by Django 3.2.14 on 2024-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0012_add_scholarship_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradprogram',
            name='expected_completion_terms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradprogram',
            name='grad_category',
            field=models.CharField(choices=[('MA', 'Masters'), ('DR', 'Doctoral'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='gradprogram',
            name='requires_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]