# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import grad.models


class Migration(migrations.Migration):

    dependencies = [
        ('grad', '0014_add_grad_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldocument',
            name='file_attachment',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=grad.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='is_canadian',
            field=models.BooleanField(null=True),
        ),
    ]
