# Generated by Django 2.2.11 on 2020-03-27 14:08

import courselib.json_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0005_on_delete'),
        ('coredata', '0022_add_new_visit_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Quiz will be visible to student after this time. Time format: HH:MM:SS, 24-hour time')),
                ('end', models.DateTimeField(help_text='Quiz will be invisible to students and unsubmittable after this time. Time format: HH:MM:SS, 24-hour time')),
                ('status', models.CharField(choices=[('V', 'Visible'), ('D', 'Deleted')], default='V', max_length=1)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='grades.Activity')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('MCM', 'Multiple Choice, multiple answer'), ('SHOR', 'Short Answer'), ('LONG', 'Long Answer'), ('NUM', 'Numeric Answer'), ('FILE', 'File Upload'), ('INST', 'Instructions (students enter nothing)')], max_length=4)),
                ('status', models.CharField(choices=[('V', 'Visible'), ('D', 'Deleted')], default='V', max_length=1)),
                ('order', models.PositiveSmallIntegerField()),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('answer', courselib.json_fields.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
            options={
                'unique_together': {('question', 'student')},
            },
        ),
    ]
