# Generated by Django 2.2.11 on 2020-04-15 14:44

import courselib.json_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0023_update_choices'),
        ('grades', '0005_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('SHOR', 'Short Answer (one line)'), ('LONG', 'Long Answer (several lines)'), ('FMT', 'Long Answer with formatting'), ('NUM', 'Numeric Answer')], max_length=4)),
                ('status', models.CharField(choices=[('V', 'Visible'), ('D', 'Deleted')], default='V', max_length=1)),
                ('order', models.PositiveSmallIntegerField()),
                ('config', courselib.json_fields.JSONField(default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Quiz will be visible to students after this time. Time format: HH:MM:SS, 24-hour time')),
                ('end', models.DateTimeField(help_text='Quiz will be invisible to students and unsubmittable after this time. Time format: HH:MM:SS, 24-hour time')),
                ('status', models.CharField(choices=[('V', 'Visible'), ('D', 'Deleted')], default='V', max_length=1)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='grades.Activity')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('V', 'Visible'), ('D', 'Deleted')], default='V', max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Question')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz'),
        ),
        migrations.CreateModel(
            name='TimeSpecialCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Quiz will be visible to the student after this time. Time format: HH:MM:SS, 24-hour time')),
                ('end', models.DateTimeField(help_text='Quiz will be invisible to the student and unsubmittable after this time. Time format: HH:MM:SS, 24-hour time')),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('answer', courselib.json_fields.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Question')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.QuestionVersion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
            options={
                'unique_together': {('question_version', 'student')},
            },
        ),
    ]
