# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MCM', 'Multiple Choice (multiple answer)'), ('SHOR', 'Short Answer'), ('LONG', 'Long Answer'), ('FMT', 'Long Answer with formatting'), ('CODE', 'Code Entry with syntax highlighting'), ('NUM', 'Numeric Answer'), ('FILE', 'File Upload')], max_length=4),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=quizzes.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='capture',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=quizzes.models.capture_upload_to),
        ),
    ]
