# Generated by Django 2.2.11 on 2020-04-02 14:33

import courselib.json_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0022_add_new_visit_data'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice, single answer'), ('SHOR', 'Short Answer (one line)'), ('LONG', 'Long Answer (several lines)'), ('FMT', 'Long Answer with formatting'), ('NUM', 'Numeric Answer')], max_length=4),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(help_text='Quiz will be visible to students after this time. Time format: HH:MM:SS, 24-hour time'),
        ),
        migrations.CreateModel(
            name='TimeSpecialCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Quiz will be visible to the student after this time. Time format: HH:MM:SS, 24-hour time')),
                ('end', models.DateTimeField(help_text='Quiz will be invisible to the student and unsubmittable after this time. Time format: HH:MM:SS, 24-hour time')),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
        ),
    ]
