# Generated by Django 2.2.11 on 2020-04-27 10:24

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionversion',
            options={'ordering': ['question', 'created_at', 'id']},
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=quizzes.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SHOR', 'Short Answer'), ('LONG', 'Long Answer'), ('FMT', 'Long Answer with formatting'), ('NUM', 'Numeric Answer')], max_length=4),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='quizzes.Question'),
        ),
    ]
