# Generated by Django 2.2.11 on 2020-05-04 09:57

import django.core.files.storage
from django.db import migrations, models
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_add_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='capture',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=quizzes.models.capture_upload_to),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SHOR', 'Short Answer'), ('LONG', 'Long Answer'), ('FMT', 'Long Answer with formatting'), ('NUM', 'Numeric Answer'), ('FILE', 'File Upload')], max_length=4),
        ),
    ]
