# Generated by Django 2.2.11 on 2020-04-14 17:51

import courselib.json_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0022_add_new_visit_data'),
        ('quizzes', '0004_unique_special_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Member')),
            ],
        ),
    ]
