from .create_course import create_course
from .create_plan import create_plan
from .admin_index import admin_index
from .copy_plan import copy_plan
from .delete_course import delete_course
from .delete_plan import delete_plan
from .delete_planned_offering import delete_planned_offering
from .edit_course import edit_course
from .edit_planned_offering import edit_planned_offering
from .edit_plan import edit_plan
from .delete_capability import delete_capability
from .delete_intention import delete_intention
from .edit_capability import edit_capability
from .edit_intention import edit_intention
from .instructor_index import instructor_index
from .submit_intention import submit_intention
from .manage_courses import manage_courses
from .planner_create_intention import planner_create_intention
from .planner_delete_capability import planner_delete_capability
from .planner_delete_intention import planner_delete_intention
from .planner_edit_capabilities import planner_edit_capabilities
from .planner_edit_intention import planner_edit_intention
from .plans_index import plans_index
from .update_plan import update_plan
from .view_capabilities import view_capabilities
from .view_instructors import view_instructors
from .view_intentions import view_intentions
from .view_plan import view_plan
from .view_semester_intentions import view_semester_intentions

from .teaching_equivalents_inst import *
from .teaching_equivalents_admin import *