# Generated by Django 3.2.25 on 2025-08-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0027_auto_20250827_1659'),
        ('groups', '0003_on_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'courseoffering'), ('slug', 'courseoffering')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='svn_slug',
        ),
    ]
