# Generated by Django 2.0.9 on 2018-11-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_on_delete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicsubscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topicsubscription',
            name='member',
        ),
        migrations.RemoveField(
            model_name='topicsubscription',
            name='topic',
        ),
        migrations.DeleteModel(
            name='TopicSubscription',
        ),
    ]
