# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 11:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_add_space_factor_and_submission_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=25),
            preserve_default=False,
        ),
    ]
