# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 15:11


import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_make_floor_and_room_number_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='space.BookingRecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.Person')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRecordAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique_with=(b'booking_record',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=b'submitted_files'), upload_to=space.models.space_attachment_upload_to)),
                ('mediatype', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('booking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='space.BookingRecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coredata.Person')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookingrecordattachment',
            unique_together=set([('booking_record', 'slug')]),
        ),
    ]
