# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 11:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_add_booking_attachments_and_memos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
