# Generated by Django 2.0.9 on 2018-11-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('ASB', 'Applied Sciences Building'), ('TASC1', 'TASC 1'), ('SRY', 'Surrey'), ('SEE', 'SEE Building'), ('PTECH', 'Powertech'), ('BLARD', 'Ballard'), ('CC1', 'CC1'), ('NTECH', 'NEUROTECH'), ('SMH', 'SMH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='campus',
            field=models.CharField(choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver')], max_length=5),
        ),
    ]
