# Generated by Django 2.2.1 on 2019-06-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_add_field_and_safety_infrastructure_to_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('STAFF', 'Staff'), ('FAC', 'Faculty'), ('PDOC', 'Post-Doc'), ('VISIT', 'Visitor'), ('SESS', 'Sessional'), ('LTERM', 'Limited-Term'), ('TA', 'TA'), ('GRAD', 'Grad Student'), ('URA', 'URA'), ('UND', 'Undergrad Student')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='key_request', to='space.BookingRecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Person')),
            ],
        ),
    ]
