# Generated by Django 2.2.4 on 2019-08-26 12:30

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_add_tracking_of_key_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sub_location',
            field=models.BooleanField(default=False, help_text='Check this if this a bookable room/desk/cubicle within another room'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date/time'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='start_time',
            field=models.DateTimeField(default=space.models.timezone_today, verbose_name='Start date/time'),
        ),
        migrations.AlterField(
            model_name='bookingrecordattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=space.models.space_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='space.RoomType'),
        ),
        migrations.AlterField(
            model_name='location',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
