# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import space.models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_make_fields_not_mandatory_and_add_sub_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrecordattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=space.models.space_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('ASB', 'Applied Sciences Building'), ('TASC1', 'TASC 1'), ('SRY', 'SRYC (Surrey Central)'), ('SEE', 'SRYE (Surrey Engineering)'), ('PTECH', 'Powertech'), ('BLARD', 'Ballard'), ('CC1', 'CC1'), ('NTECH', 'NEUROTECH'), ('SMH', 'SMH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='sub_location',
            field=models.BooleanField(default=False, help_text='Check this if this a bookable room/desk/cubicle within another room', verbose_name='Sub-Location/Room/Desk/Cubicle'),
        ),
    ]
