# Generated by Django 2.0.13 on 2019-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0007_add_new_visit_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorvisit',
            name='category',
        ),
        migrations.AddField(
            model_name='advisorvisit',
            name='categories',
            field=models.ManyToManyField(to='advisornotes.AdvisorVisitCategory'),
        ),
    ]
