# Generated by Django 2.0.13 on 2019-03-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0008_fix_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorvisit',
            name='campus',
            field=models.CharField(blank=True, choices=[('BRNBY', 'Burnaby Campus'), ('SURRY', 'Surrey Campus'), ('VANCR', 'Harbour Centre'), ('OFFST', 'Off-campus'), ('GNWC', 'Great Northern Way Campus'), ('METRO', 'Other Locations in Vancouver')], max_length=5, null=True),
        ),
    ]
