# Generated by Django 2.0.13 on 2019-03-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0009_add_campus_to_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorvisit',
            name='hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='advisorvisit',
            name='campus',
            field=models.CharField(choices=[('BRNBY', 'Burnaby'), ('SURRY', 'Surrey'), ('VANCR', 'Vancouver')], default='BRNBY', max_length=5),
            preserve_default=False,
        ),
    ]
