# Generated by Django 2.2.15 on 2020-12-09 23:55

import advisornotes.models
import courselib.json_fields
import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('advisornotes', '0010_change_campus_choice_and_allow_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('author', models.ForeignKey(editable=False, help_text='The user who created the news item', on_delete=django.db.models.deletion.PROTECT, related_name='posted_by', to='coredata.Person')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
