# Generated by Django 2.2.15 on 2020-12-18 11:14

import advisornotes.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('advisornotes', '0011_advisor_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='unit',
            field=models.ForeignKey(default=0, help_text='Academic unit who owns the note', on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advisornote',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=advisornotes.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='artifactnote',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=advisornotes.models.attachment_upload_to),
        ),
    ]
