# Generated by Django 3.2.14 on 2023-04-19 15:52

import advisornotes.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0012_announcement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advisornote',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=advisornotes.models.attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='artifactnote',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=384, location='submitted_files'), upload_to=advisornotes.models.attachment_upload_to),
        ),
    ]
