# Generated by Django 3.2.14 on 2024-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0013_auto_20230419_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorvisit',
            name='mode',
            field=models.CharField(choices=[('IP', 'In-Person'), ('R', 'Remote'), ('N', '')], default='N', max_length=2),
        ),
    ]
