# Generated by Django 3.2.14 on 2024-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0015_alter_advisorvisit_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstudent',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
