# Generated by Django 3.2.14 on 2025-08-11 15:22

import courselib.json_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advisornotes', '0016_nonstudent_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorVisitSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unsure')], max_length=2, null=True)),
                ('overall', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Very Good'), (3, 'Good'), (2, 'Fair'), (1, 'Needs Improvement')], null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('questions_answered', models.CharField(blank=True, choices=[('Y', 'Yes, Completely'), ('PY', 'Partially, they said they would follow up'), ('PN', 'Partially, they did not say they would follow up'), ('N', 'No'), ('NA', 'Not Applicable/No Specific Question')], max_length=2, null=True)),
                ('support', models.IntegerField(blank=True, choices=[(5, 'Strongly Agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly Disagree')], null=True)),
                ('advisor_review', models.CharField(blank=True, max_length=255, null=True)),
                ('questions_unanswered', models.CharField(blank=True, choices=[('NT', 'There was not enough time in the appointment'), ('NI', 'The advisor did not have the information needed'), ('FU', 'The advisor needed to follow up or consult with another department'), ('CC', 'The question related to curriculum (eg. course offerings, scheduling, substitutions), was not something advising could change'), ('OR', "The question was outside the advisor's role or responsibilities"), ('OT', 'Other (please specify)')], max_length=2, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=500)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.person')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey', to='advisornotes.advisorvisit')),
            ],
        ),
    ]
