# Generated by Django 4.2.23 on 2026-01-19 16:32

import courselib.uuid
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("advisornotes", "0018_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorvisitsurvey",
            name="key",
            field=courselib.uuid.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
