# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:09
from __future__ import unicode_literals

import autoslug.fields
import courselib.json_fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0009_add_prefix_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_prefix',
            field=models.CharField(blank=True, help_text="If the project number has a prefix of 'R', 'X', etc, add it here", max_length=1, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='account',
            field=models.ForeignKey(help_text='This is now called "Object" in the new PAF', on_delete=django.db.models.deletion.PROTECT, to='ra.Account'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='comments',
            field=models.TextField(blank=True, help_text='For internal use', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='dental_benefits',
            field=models.BooleanField(default=False, help_text='50% of Dental Plan'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='hiring_category',
            field=models.CharField(choices=[('U', 'Undergrad'), ('E', 'Grad Employee'), ('N', 'Non-Student'), ('S', 'Grad Scholarship'), ('RA', 'Research Assistant'), ('RSS', 'Research Services Staff'), ('PDF', 'Post Doctoral Fellow'), ('ONC', 'Other Non Continuing'), ('RA2', 'University Research Assistant (Min of 2 years with Benefits)'), ('RAR', 'University Research Assistant (Renewal after 2 years with Benefits)'), ('GRA', 'Graduate Research Assistant'), ('NS', 'National Scholarship')], default='GRA', max_length=4),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='hiring_faculty',
            field=models.ForeignKey(help_text='The manager who is hiring the RA.', on_delete=django.db.models.deletion.PROTECT, related_name='ra_hiring_faculty', to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Biweekly Hours'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='lump_sum_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Hours'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='lump_sum_pay',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Pay'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='medical_benefits',
            field=models.BooleanField(default=False, help_text='50% of Medical Service Plan'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Biweekly employment earnings rates must include vacation pay, hourly rates will automatically have vacation pay added. The employer cost of statutory benefits will be charged to the amount to the earnings rate.', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='offer_letter_text',
            field=models.TextField(help_text='Text of the offer letter to be signed by the RA and supervisor.', null=True),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='pay_frequency',
            field=models.CharField(choices=[('B', 'Biweekly'), ('L', 'Lump Sum')], default='B', max_length=60),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='person',
            field=models.ForeignKey(help_text='The RA who is being appointed.', on_delete=django.db.models.deletion.PROTECT, related_name='ra_person', to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='program',
            field=models.ForeignKey(blank=True, help_text='If none is provided,  "00000" will be added in the PAF', null=True, on_delete=django.db.models.deletion.PROTECT, to='ra.Program'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ra.Project'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='reappointment',
            field=models.BooleanField(default=False, help_text='Are we re-appointing to the same position?'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='scholarship',
            field=models.ForeignKey(blank=True, help_text='Scholarship associated with this appointment. Optional.', null=True, on_delete=django.db.models.deletion.PROTECT, to='grad.Scholarship'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='unit',
            field=models.ForeignKey(help_text='The unit that owns the appointment', on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
        migrations.AlterField(
            model_name='raappointment',
            name='visa_verified',
            field=models.BooleanField(default=False, help_text="I have verified this RA's visa information"),
        ),
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='ra.RAAppointment'),
        ),
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='submitted_files'), upload_to=ra.models.ra_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='created_by',
            field=models.ForeignKey(help_text='Document attachment created by.', on_delete=django.db.models.deletion.PROTECT, to='coredata.Person'),
        ),
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('appointment',)),
        ),
        migrations.AlterField(
            model_name='semesterconfig',
            name='config',
            field=courselib.json_fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='semesterconfig',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Semester'),
        ),
        migrations.AlterField(
            model_name='semesterconfig',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit'),
        ),
    ]
