# Generated by Django 2.2.15 on 2021-01-17 20:07

import autoslug.fields
import courselib.json_fields
import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('ra', '0010_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_attachment_upload_to),
        ),
        migrations.CreateModel(
            name='RARequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonstudent', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=80, null=True)),
                ('student', models.CharField(choices=[('N', 'Appointee is NOT a student'), ('U', 'Undergraduate Student'), ('M', 'Masters Student'), ('P', 'PhD Student')], default=None, max_length=80)),
                ('coop', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('mitacs', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('thesis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('people_comments', models.TextField(blank=True)),
                ('hiring_category', models.CharField(choices=[('GRAS', 'Graduate Research Assistant Scholarship'), ('RA', 'Research Assistant')], default=None, max_length=80)),
                ('gras_payment_method', models.CharField(choices=[('BW', 'Biweekly salary for students with Canadian bank account.'), ('LE', 'Lump sum payment for students with Canadian bank account (Funds will be paid at the end of the appointment term)'), ('LS', 'Lump sum payment for students without Canadian bank account (Funds will be paid at the START of the appointment term to the individuals student account)')], default='', max_length=80)),
                ('ra_payment_method', models.CharField(choices=[('BW', 'Bi-weekly salary (The Appointee is entitled to a minimum of 10 vacation days a year per FTE. Vacation time will be prorated based on the appointment terms. An additional 10% will be charged for statutory benefits.)'), ('H', 'Hourly (4% vacation pay will be deducted from the project in addition to 10% for statutory benefits. Must submit biweekly timesheets in order for the Appointee to be paid.)')], default='', max_length=80)),
                ('total_gross', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('gross_hourly', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('vacation_pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('biweekly_pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('days_vacation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('biweekly_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fs1_unit', models.CharField(max_length=80)),
                ('fs1_fund', models.CharField(max_length=80)),
                ('fs1_project', models.CharField(max_length=80)),
                ('fs2_option', models.BooleanField(default=False)),
                ('fs2_unit', models.CharField(blank=True, max_length=80, null=True)),
                ('fs2_fund', models.CharField(blank=True, max_length=80, null=True)),
                ('fs2_project', models.CharField(blank=True, max_length=80, null=True)),
                ('file_attachment_1', models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to)),
                ('file_mediatype_1', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('file_attachment_2', models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to)),
                ('file_mediatype_2', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('funding_comments', models.TextField(blank=True)),
                ('ra_benefits', models.CharField(choices=[('Y', "Yes (The cost will be shared 50/50 between employee and employer and eligibility depends on your funding source.An additional 2% to 4% of salary costs will be added to your project. Cost depends on Appointee's dependents and family size.)"), ('NE', 'No - My grant is not eligible.'), ('N', 'No')], default='', max_length=80)),
                ('ra_duties_ex', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_dc', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_pd', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_im', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_eq', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_su', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_wr', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_pm', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties', models.TextField(blank=True)),
                ('ra_other_duties', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_author', to='coredata.Person')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_person', to='coredata.Person')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_supervisor', to='coredata.Person')),
            ],
        ),
    ]
