# Generated by Django 2.2.15 on 2021-02-01 10:20

import autoslug.fields
import courselib.json_fields
import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('ra', '0010_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_attachment_upload_to),
        ),
        migrations.CreateModel(
            name='RARequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonstudent', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=80, null=True)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('hiring_category', models.CharField(choices=[('GRAS', 'Graduate Research Assistant Scholarship'), ('RA', 'Research Assistant')], default=None, max_length=80)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file_attachment_1', models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to)),
                ('file_mediatype_1', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('file_attachment_2', models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to)),
                ('file_mediatype_2', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('ra_duties_ex', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_dc', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_pd', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_im', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_eq', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_su', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_wr', models.CharField(blank=True, max_length=500, null=True)),
                ('ra_duties_pm', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_author', to='coredata.Person')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_person', to='coredata.Person')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_supervisor', to='coredata.Person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.Unit')),
            ],
        ),
    ]
