# Generated by Django 2.2.15 on 2021-02-08 17:09

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('ra', '0011_add_ra_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='RARequestAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('req',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, file_permissions_mode=420, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to)),
                ('mediatype', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('created_by', models.ForeignKey(help_text='Attachment created by.', on_delete=django.db.models.deletion.PROTECT, to='coredata.Person')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='ra.RARequest')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('req', 'slug')},
            },
        ),
    ]
