# Generated by Django 2.2.15 on 2021-04-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0024_longer_userid'),
        ('ra', '0012_rarequestattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rarequest',
            name='file_mediatype_1',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='file_mediatype_2',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_dc',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_eq',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_ex',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_im',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_pd',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_pm',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_su',
        ),
        migrations.RemoveField(
            model_name='rarequest',
            name='ra_duties_wr',
        ),
        migrations.AddField(
            model_name='rarequest',
            name='backdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='biweekly_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='biweekly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='coop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs1_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs1_project',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs1_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs2_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs2_project',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs2_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs3_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs3_project',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='fs3_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='gras_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Biweekly salary for students with Canadian bank account.'), ('LE', 'Lump sum payment for students with Canadian bank account (Funds will be paid at the end of the appointment term)'), ('LS', 'Lump sum payment for students without Canadian bank account (Funds will be paid at the START of the appointment term to the individuals student account)')], default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='gross_hourly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='last_updater',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rarequest_last_updater', to='coredata.Person'),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='mitacs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='nc_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Bi-weekly salary (The Appointee is entitled to a minimum of 10 vacation days a year per FTE. Vacation time will be prorated based on the appointment terms. An additional 10% will be charged for statutory benefits.)'), ('H', 'Hourly (4% vacation pay will be deducted from the project in addition to 10% for statutory benefits. Must submit biweekly timesheets in order for the Appointee to be paid.)')], default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='offer_letter_text',
            field=models.TextField(default='', help_text='Text of the offer letter to be signed by the RA and supervisor.', null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='position',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='ra_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Bi-weekly salary (The Appointee is entitled to a minimum of 10 vacation days a year per FTE. Vacation time will be prorated based on the appointment terms. An additional 10% will be charged for statutory benefits.)'), ('H', 'Hourly (4% vacation pay will be deducted from the project in addition to 10% for statutory benefits. Must submit biweekly timesheets in order for the Appointee to be paid.)')], default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='research',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='science_alive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='student',
            field=models.CharField(choices=[('N', 'Appointee is NOT a student'), ('U', 'Undergraduate Student'), ('M', 'Masters Student'), ('P', 'PhD Student')], default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='thesis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='vacation_hours',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='vacation_pay',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='weeks_vacation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='hiring_category',
            field=models.CharField(choices=[('GRAS', 'Graduate Research Assistant Scholarship'), ('RA', 'Research Assistant'), ('NC', 'Other Non-Continuing')], default=None, max_length=80),
        ),
    ]
