# Generated by Django 2.2.15 on 2021-05-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0013_update_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarequest',
            name='file_mediatype_1',
            field=models.CharField(blank=True, default=None, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rarequest',
            name='file_mediatype_2',
            field=models.CharField(blank=True, default=None, editable=False, max_length=200, null=True),
        ),
    ]
