# Generated by Django 2.2.15 on 2021-06-29 16:25

import django.core.files.storage
from django.db import migrations, models
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0015_update_decimal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarequest',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
