# Generated by Django 3.2.25 on 2025-08-27 17:01

import django.core.files.storage
from django.db import migrations, models
import ra.models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0017_add_processor_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raappointmentattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ra.models.ra_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='file_attachment_1',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='file_attachment_2',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='gras_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Biweekly funding for students with Canadian bank account.'), ('LE', 'Lump sum payment for students with Canadian bank account (Funds will be paid at the end of the appointment term)')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='nc_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Bi-weekly salary (The Appointee is entitled to a minimum of 10 vacation days a year per FTE. Vacation time will be prorated based on the appointment terms. An additional 11% will be charged for statutory benefits.)'), ('H', 'Hourly (4% vacation pay will be deducted from the project in addition to 11% for statutory benefits. Must submit biweekly timesheets in order for the Appointee to be paid.)'), ('LS', 'Lump Sum Amount')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rarequest',
            name='ra_payment_method',
            field=models.CharField(blank=True, choices=[('BW', 'Yes (Salaried - The Appointee is entitled to a minimum of 10 vacation days a year. Vacation time will be pro-rated based on the appointment terms.)'), ('H', 'No (Hourly - The Appointee will receive 4% vacation pay. Timesheet must be submitted biweekly for the Appointee to be paid.)')], default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rarequestattachment',
            name='contents',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=ra.models.ra_request_attachment_upload_to),
        ),
    ]
