# Generated by Django 5.2.17 on 2026-09-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ra", "0018_trivial_migration_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rarequest",
            name="nc_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "BW",
                        "Bi-weekly salary (The Appointee is entitled to a minimum of 10 vacation days a year per FTE. Vacation time will be prorated based on the appointment terms. An additional 11% will be charged for statutory benefits.)",
                    ),
                    (
                        "H",
                        "Hourly (Vacation pay % will be deducted from the project in addition to 11% for statutory benefits. Must submit biweekly timesheets in order for the Appointee to be paid.)",
                    ),
                    ("LS", "Lump Sum Amount"),
                ],
                default=None,
                max_length=80,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rarequest",
            name="ra_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "BW",
                        "Yes (Salaried - The Appointee is entitled to a minimum of 10 vacation days a year. Vacation time will be pro-rated based on the appointment terms.)",
                    ),
                    (
                        "H",
                        "No (Hourly - The Appointee will receive vacation pay in lieu of vacation time. Timesheet must be submitted biweekly for the Appointee to be paid.)",
                    ),
                ],
                default=None,
                max_length=80,
                null=True,
            ),
        ),
    ]
