# Generated by Django 4.2.30 on 2026-08-06 16:45

import autoslug.fields
import courselib.json_fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import postdoc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0028_alter_role_role_alter_roleaccount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL_SFU', 'External (paid through SFU)'), ('EXTERNAL_NON_SFU', 'External (not paid through SFU)'), ('BOTH', 'Both Internal and External')], max_length=24)),
                ('doctorate_completed_date', models.DateField()),
                ('work_eligibility_status', models.CharField(choices=[('CANADIAN_CITIZEN', 'Canadian Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident'), ('INTERNATIONAL', 'International')], max_length=24)),
                ('relocation_reimbursement', models.BooleanField(default=False)),
                ('relocation_reimbursement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('involved_teaching', models.BooleanField(default=False)),
                ('other_info', models.CharField(blank=True, default='', max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('benefits_estimation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('work_hours', models.CharField(choices=[('FULL_TIME', 'Full Time (35 hours/week)'), ('PART_TIME', 'Part Time'), ('EXT', 'External'), ('LS', 'Lump Sum')], default='FULL_TIME', max_length=16)),
                ('hours_of_work', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('vacation_entitlement_weeks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('annual_salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('lump_sum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('admin_notes', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('config', courselib.json_fields.JSONField(default=dict)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='autoslug', unique=True)),
                ('last_updater', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postdoc_last_updater', to='coredata.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postdoc_person', to='coredata.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.unit')),
            ],
            options={
                'ordering': ['person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PostDocFundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=0)),
                ('fund', models.IntegerField(default=0)),
                ('project', models.CharField(blank=True, default='', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('postdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='postdoc.postdoc')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PostDocSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_links', to='postdoc.postdoc')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postdoc_supervisor_links', to='coredata.person')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('postdoc', 'supervisor')},
            },
        ),
        migrations.CreateModel(
            name='PostDocAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('appt',))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url=None, directory_permissions_mode=448, file_permissions_mode=384, location='submitted_files'), upload_to=postdoc.models.postdoc_attachment_upload_to)),
                ('mediatype', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('hidden', models.BooleanField(default=False, editable=False)),
                ('appt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='postdoc.postdoc')),
                ('created_by', models.ForeignKey(help_text='Attachment created by.', on_delete=django.db.models.deletion.PROTECT, to='coredata.person')),
            ],
            options={
                'ordering': ('created_at',),
                'unique_together': {('appt', 'slug')},
            },
        ),
    ]
