' To generate diagram:
' sudo apt install plantuml
' plantuml arch.puml 

' https://github.com/plantuml/plantuml-stdlib/tree/master/stdlib/logos

@startuml

!include <logos/nginx>
!include <logos/gunicorn>
!include <logos/django>
!include <logos/rabbitmq>
!include <logos/ruby>
!include <logos/python>
!include <logos/rabbitmq>
!include <logos/memcached>
!include <logos/elasticsearch>
!include <logos/mariadb>

actor Users as users

agent "SFUCloud Load Balancer\n(terminates HTTPS)" as lb

users <-> lb : HTTPS

package "Production Server" {
    actor Admins
    package "Docker" {    
        folder "static" as static
        control "Daily Import\nTask" as import
        
        agent "<$python>\nCelery" as celery
        agent "Celerybeat" as celerybeat
        agent "<$nginx>\nNginx" as nginx
        agent "<$python>\nGunicorn" as gunicorn

        queue "<$rabbitmq>\nRabbitMQ" as rabbitmq
        database "<$memcached>\nMemcached" as memcached
        database "<$elasticsearch>\nElasticsearch" as elasticsearch
        agent "Logrotate" as logrotate

        static <-- gunicorn  : "compressor"
        'gunicorn --> static : "compressor"
        nginx <-- static : "static\nfiles"
        nginx <---> gunicorn : "dynamic\npages"
        
        gunicorn ..> rabbitmq : tasks
        celery <.. rabbitmq : tasks
        gunicorn <--> memcached : cache
        gunicorn <--> elasticsearch : search
        rabbitmq <.. celerybeat : periodic\ntasks
        import <... celery : runs

        control "manage\ncollectstatic" as collectstatic
    }

    folder "nginx_logs" as nginx_logs
    nginx_logs <-- nginx : writes
    nginx_logs <.. logrotate : rotates

    folder "submitted_files\n(NFS share)" as files
    gunicorn <--> files
    celery <--> files

}

package "Onara" {
    database "<$mariadb>\nDatabase" as db
}

lb <--> nginx : HTTP
db <--> gunicorn
db <--> celery
db <- import



'package "External APIs" {
    database "CSRPT" as csrpt
    agent "CAS" as cas
    database "Photo API" as photo
    database "AMAINT" as amaint
    cloud "smtpserver.sfu.ca" as email
'}

import <-- csrpt
'csrpt --> celery
csrpt --> gunicorn
gunicorn <..> cas : auth
celery <-- photo : photos
email <- celery : "outgoing email"
import <-- amaint

'static <- collectstatic : "writes"
collectstatic -> static : "writes"


@enduml
